### ISSUE TITLE
tab_separator_lines.css ineffective on Linux

### ISSUE THREAD

**Issue by ceodoe** [MrOtherGuy/firefox-csshacks#108]
tab_separator_lines.css doesn't seem to work on Linux. My load order is as follows:

```
@import url("chrome/compact_proton.css");
@import url("chrome/non_floating_sharp_tabs.css");
@import url("chrome/tab_separator_lines.css");
@import url("chrome/iconized_main_menu.css");
@import url("chrome/inline_tab_audio_icons.css");
@import url("chrome/autohide_bookmarks_and_main_toolbars.css");
@import url("chrome/compact_urlbar_megabar.css");
```

...although changing the load order doesn't seem to make any difference. Disabling all other styles also doesn't do anything. Using Firefox 89.0+build2-0ubuntu0.20.04.2 amd64 from Ubuntu Focal repo. Any ideas? 🤔

**Comment by mnxn** [comment]
I noticed the same thing on Windows.

My workaround was to use some of the old photon CSS:
```css
.titlebar-spacer[type="pre-tabs"] {
	border-inline-end: 1px solid
		var(--lwt-background-tab-separator-color, currentColor);
	opacity: 0.2;
}

.tabbrowser-tab::after,
.tabbrowser-tab::before {
	border-left: 1px solid
		var(--lwt-background-tab-separator-color, currentColor);
	opacity: 0.3;
}

.tabbrowser-tab::before {
	margin-inline-start: -1px;
}

.tabbrowser-tab::after,
#tabbrowser-tabs[movingtab]
	> #tabbrowser-arrowscrollbox
	> .tabbrowser-tab[visuallyselected]::before {
	content: "";
	display: block;
}
```
