### ISSUE TITLE
Pinned Tabs in non_floating_sharp_tabs.css

### ISSUE THREAD

**Issue by Wombat2018** [MrOtherGuy/firefox-csshacks#118]
Hi,

one further thing which I noticed in non_floating_sharp_tabs.css:

I think in previous Firefox versions the pinned tabs were displayed as the selected tab (not pinned), so that they stood out compared to other non unpinned tabs.

Maybe you can give me a hint or make this optional.

**Comment by MrOtherGuy** [comment]
I don't think that was ever the case without some custom css to do just that. But you could use this to do it with non_floating_sharp_tabs.css

```css
.tabbrowser-tab[pinned] > stack > .tab-background::before{
  display: -moz-box;
  height: 2px;
  content: "";
  background-color: highlight;
  background-image: linear-gradient(var(--tab-line-color),var(--tab-line-color));
}
.tabbrowser-tab[pinned] > stack > .tab-background{
  border-inline: 1px solid var(--tabs-border-color) !important;
  background-attachment: scroll, scroll, fixed;
  background-color: transparent;
  background-image: linear-gradient(var(--lwt-selected-tab-background-color, transparent), var(--lwt-selected-tab-background-color, transparent)), linear-gradient(var(--toolbar-bgcolor), var(--toolbar-bgcolor)), var(--lwt-header-image, none);
  background-position: 0 0, 0 0, right top;
  background-repeat: repeat-x, repeat-x, no-repeat;
  background-size: auto 100%, auto 100%, auto auto;
}
.tabbrowser-tab[pinned]{ z-index: 2 }
```
