### ISSUE TITLE
Tabs on bottom IE like, compatibility

### ISSUE THREAD

**Issue by black7375** [MrOtherGuy/firefox-csshacks#145]
https://github.com/black7375/Firefox-UI-Fix/wiki/Tips#tabs-on-bottom
As I was writing the code for the wiki, I discovered a few things that could be improved.
I'll create a PR if you want.

1. IE like mode

![](https://user-images.githubusercontent.com/25581533/133336720-ee26817d-d3de-4690-b82a-6c9c5ab06e17.png)
We can think of an IE-like mode where the bookmarks are below the tab bar.

When using option `Only Show on New tab`, the position of the tab bar does not change, so it is a reasonable choice.

We can add the following code to https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/tabs_on_bottom.css
```css
/* If Do you want like IE, Add this  */
/*
#PersonalToolbar {
  -moz-box-ordinal-group: 2;
}
*/
```

2. Color

When the tab is attached to the toolbar, the color at the bottom should be the same.
https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/combined_tabs_and_main_toolbars.css

We can add the following code to https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/tabs_on_bottom.css
```css
/* Navigator toolbox bottom border.
   Use combined_tabs_and_main_toolbars.css, if not IE mode, Add this:
 */
/*
#navigator-toolbox {
  border-bottom-color: var(--toolbar-bgcolor) !important; /* Original: 1px solid var(--chrome-content-separator-color); */
}
*/
```

3. Padding at maxize

When maximized, `prev spacing`'s padding should disappear.
This is the default behavior of Firefox.
https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/window_control_placeholder_support.css

```css
:root[tabsintitlebar] {
  --uc-window-drag-space-pre: 30px; /* Same as .titlebar-spacer[type="pre-tabs"]  - Extra space reserved on both sides of the nav-bar to be able to drag the window */
  --uc-window-drag-space-post: 30px; /* Same as .titlebar-spacer[type="post-tabs"] */
}
:root[tabsintitlebar][sizemode="maximized"] {
  --uc-window-drag-space-pre: 0px; /* Remove pre space */
}

#nav-bar {
  border-inline-start-width: var(--uc-window-drag-space-pre, 0px);
  border-inline-end-width: calc(var(--uc-window-control-width, 0px) + var(--uc-window-drag-space-post, 0px));
}

@supports -moz-bool-pref("layout.css.osx-font-smoothing.enabled") {
  :root[tabsintitlebar="true"]:not([inFullscreen]) #nav-bar {
    border-inline-start-width: calc(var(--uc-window-control-width, 0px) + var(--uc-window-drag-space-post, 0px));
    border-inline-end-width: var(--uc-window-drag-space-pre, 0px);
  }
}
```

4. Padding at Each platform

The size of `.titlebar-buttonbox-container` on each platform.
https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/window_control_placeholder_support.css

```css
@media (-moz-os-version: windows-win7), (-moz-os-version: windows-win8) {
  :root[tabsintitlebar] {
    --uc-window-control-width: 105px;
  }
}

@media (-moz-gtk-csd-available) {
  :root[tabsintitlebar] {
    --uc-window-control-width: 84px;
  }
}
```

5. Consider Menu bar

When we have a menu bar, we need to consider the button position.
https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/window_control_placeholder_support.css

```css
/* At Activated Menubar */
:root:not([chromehidden~="menubar"]) #toolbar-menubar:not([autohide="true"]) + #TabsToolbar > .titlebar-buttonbox-container {
  display: block !important;
}
:root:not([chromehidden~="menubar"]) #toolbar-menubar:not([autohide="true"]) .titlebar-buttonbox-container {
  visibility: hidden;
}
```
