### ISSUE TITLE
tab content will jump when cursor hover in centered_tab_content.css

### ISSUE THREAD

**Issue by 921j** [MrOtherGuy/firefox-csshacks#156]
I like centered_tab_content's effect but there's a little issue：
FX93
Whenever the mouse hovers over a tab with the centered content, the content will jump once, no matter whether it has been activated or not, the pined tab or the tab full of content will not.
This question is similar to this description, but it jumps to the left, mine jumps to the right
[https://github.com/black7375/Firefox-UI-Fix/issues/71#issuecomment-857103564](url)
Please tell me how to keep it from beating, thanks!

**Comment by MrOtherGuy** [comment]
Sorry but I can't reproduce that. I would imagine that if you customize tab close buttons somehow then this issue could certainly happen, but I don't think it's because of this style.

You should probably confirm by only using this style and seeing if the issue persists.

**Comment by 921j** [comment]
> Sorry but I can't reproduce that. I would imagine that if you customize tab close buttons somehow then this issue could certainly happen, but I don't think it's because of this style.
> 
> You should probably confirm by only using this style and seeing if the issue persists.

Yes! I hide the tab close buttons use this:
```
.tabbrowser-tab .tab-close-button {
  visibility: collapse !important;
}
```
When I disable it the content don't jump！
Is there any way to make these two effects exist at the same time and the content no longer jumps?PLZ！

**Comment by MrOtherGuy** [comment]
I think you can remove the last line of the centered_tab_label.css yo achieve that.

**Comment by 921j** [comment]
> I think you can remove the last line of the centered_tab_label.css yo achieve that.

no, I'ts still jump，I'll try more snippets about hide close button.

**Comment by AndhikaWB** [comment]
I can reproduce similar issue (using latest commit) when centered tabs label is used together with compact proton (Firefox 108, Linux, KDE). It's not a big deal but I hope it could be fixed.

**Comment by MrOtherGuy** [comment]
Does it happen *only* if you also use compact_proton.css ? And does it happen with both normal and compact toolbar densities (changed in customization mode)?

**Comment by AndhikaWB** [comment]
After some more observations, it does happen when using it together with `compact_proton.css` and also without it (with slightly different behavior).

When used together with `compact_proton.css`, the tab label jumps on unpinned tab when hovered by cursor (whether it's active or not) AND pinned tab if it's the current active tab when not covered by cursor.

When used alone, the tab label jumps ONLY on pinned active tab when hovered by cursor (doesn't happen if pinned tab is not active).

It does only happen if the tab title isn't long enough to cover the entire tab box space (e.g. new tab), I think.

> And does it happen with both normal and compact toolbar densities (changed in customization mode)?

Compact mode doesn't appear when in customization mode (only normal and touch is selectable), that's why I use the script. The bug also applies on touch mode though.

**Comment by MrOtherGuy** [comment]
Having it happen on on selected tab sort of sounds like it may have something to do with tab-close-button styling, but the style should already work around that. So, unless you have some *other* custom styles that modify tabs then I don't really understand what is going wrong. 

For the record, I can't see any jumpiness in compact (you need to enable compact density in about:config for it to show up), normal or touch densities.

**Comment by AndhikaWB** [comment]
Weird, I already tried disabling any other modification and the result is still the same (see attached video). Enabling compact mode from customize toolbar doesn't make any difference either (still jumpy but only on pinned active tab, when `compact_proton.css` is disabled).

https://user-images.githubusercontent.com/17119394/212318917-7a600357-bf5a-4cdc-a173-ebaefa559d4a.mp4

> Having it happen on on selected tab sort of sounds like it may have something to do with tab-close-button styling, but the style should already work around that.

Is there other required style file that need to be used together with it? I checked the CSS file and there's no mention of other required file. Tried together with `tab_close_button_always_on_hover.css` (if that's what you mean) and still jumpy too, even on pinned tab where the close button didn't exist.

**Comment by AndhikaWB** [comment]
I fixed it, change these lines in `centered_tab_label.css`:
``` css
.tabbrowser-tab[selected]:not(:hover) .tab-label-container:not([labeldirection="rtl"]),
#tabbrowser-tabs:not([closebuttons="activetab"]) .tabbrowser-tab:not(:hover,[pinned]) .tab-label-container:not([labeldirection="rtl"]){
  margin-inline-end: 7px;
}
```

with these (just add `[pinned]` after `.tabbrowser-tab[selected]:not(:hover)` ):
``` css
.tabbrowser-tab[selected]:not(:hover,[pinned]) .tab-label-container:not([labeldirection="rtl"]),
#tabbrowser-tabs:not([closebuttons="activetab"]) .tabbrowser-tab:not(:hover,[pinned]) .tab-label-container:not([labeldirection="rtl"]){
  margin-inline-end: 7px;
}
```
