### ISSUE TITLE
Navbar tabs oneliner tab height is too big

### ISSUE THREAD

**Issue by emmarvpol** [MrOtherGuy/firefox-csshacks#171]
Hello! Thanks for your amazing work!

I have an issue. I just add the css of navbar_tabs_oneliner.css to my userChrome.css and it works but the height of the tabs is greater then navbar. You can see the screenshot bellow.

[firefox-tabs-height-problem.png](https://postimg.cc/G8QDqSQ8)

Thanks you very much!

**Comment by MrOtherGuy** [comment]
This might be related to #169 

As such, you might want to test if this bit of CSS helps:
```css
#tabbrowser-tabs:not([secondarytext-unsupported]) .tab-label-container{
  height: min(2.7em, var(--tab-min-height)) !important;
}
.tab-label{ line-height: 1.2 !important; }
```

Also, does this happen with just navbar_tabs_oneliner.css or do you have other changes as well?

**Comment by eribertomota** [comment]
Hi @MrOtherGuy,

I saw the possible solutions in #169 and this procedure solved the problem for me. Debian 11 Bullseye with Firefox 91.6.0esr.

Thanks a lot for your help.

**Comment by emmarvpol** [comment]
Yeah! This solves my problem too! Thanks you very much!!
[![firefox-tabs-height-problem-fixed.png](https://i.postimg.cc/jdFCDtyB/firefox-tabs-height-problem-fixed.png)](https://postimg.cc/Wh0sKRW7)

**Comment by MrOtherGuy** [comment]
Cool, good to know. I really would like to figure out what exactly causes this in the first place. I haven't yet been able to reproduce the issue in my Fedora 35 or Windows 10 so if anyone has ideas what I need to do to reproduce it I'm all ears.

**Comment by eribertomota** [comment]
But after restart twice Firefox, the problem goes back.

**Comment by eribertomota** [comment]
> Cool, good to know. I really would like to figure out what exactly causes this in the first place. I haven't yet been able to reproduce the issue in my Fedora 35 or Windows 10 so if anyone has ideas what I need to do to reproduce it I'm all ears.

Debian 11 with Firefox via apt install firefox-esr.

**Comment by eribertomota** [comment]
I use KDE Plasma and my fonts are 10pt.

**Comment by emmarvpol** [comment]
Im using i3-gaps with Monofur Nerd Font 14.
I tried it to my virtual machine with xfce4, firefox 91.5.0esr, font: Cantarell regular 11 and its working without any problem.
I will try to change some fonts to see.

**Comment by eribertomota** [comment]
I don't know if I am a bit confuse in this topic. My problem is related to described in #169. The vertical size of the tabs was increased in FF 91. The space between the rows too. I use 7 rows.

**Comment by MrOtherGuy** [comment]
Yeah, Cantarell regular at 11pt works fine for me - and a whole bunch of other fonts too.

At this point all I can say that it definitely is affected by text size. I could add this "fix" to affected stylesheets I guess. It would cause a small unfortunate side-effect for folks who don't experience any issue though, so I'm trying to figure out how to make it less "destructive"

> In a first moment, the changes above solved this issue. However, after a new restart, the problem gone back.

That sounds very weird - I have no idea what might be causing that. But sure, if this "fix" isn't working then it's expected that tab rows are too tall. I'm 95% sure that the same underlying thing causes both issues.

**Comment by MrOtherGuy** [comment]
Could you folks test if this bit would solve the issue:

```css
#tabbrowser-tabs:not([secondarytext-unsupported]) .tab-label-container{
  height: var(--tab-min-height) !important;
}
.tab-label{ line-height: 20px !important; }
:root[uidensity="compact"] .tab-label{ line-height: 18px !important; }
```

Using fixed size line-height size line-height should not mess up layout so much for unaffected systems - I hope.

**Comment by emmarvpol** [comment]
Sure. I tried and its fixing the problem. The first one fixed my problem too.
I mean this on:
```
#tabbrowser-tabs:not([secondarytext-unsupported]) .tab-label-container{
  height: min(2.7em, var(--tab-min-height)) !important;
}
.tab-label{ line-height: 1.2 !important; }
```

**Comment by MrOtherGuy** [comment]
Alright, thanks.

I wonder if it would be better to add a separate file just for this "fix" though, since there are a whole lot of styles that would need it. I wouldn't want to add these rules to all of them if it could be avoided. But I don't know just yet what the best course of action would be.

**Comment by eribertomota** [comment]
Hi @MrOtherGuy,

The last suggestion didn't solve the problem for me.

Thanks!

![ff71](https://user-images.githubusercontent.com/6435502/153752997-37946727-7d1f-4887-9a20-92bf9b7b7e76.jpg)

**Comment by MrOtherGuy** [comment]
@eribertomota That's unfortunate for sure, but previously you said that the previous snippet helped at first but then it suddenly didn't. To me that sounds like there may be something else going on on your setup *in addition* to this problem.

Does your userChrome.css contain anything else except contents of multi-row_tabs.css followed by this snippet:

```css
#tabbrowser-tabs:not([secondarytext-unsupported]) .tab-label-container{
  height: var(--tab-min-height) !important;
}
.tab-label{ line-height: 20px !important; }
:root[uidensity="compact"] .tab-label{ line-height: 18px !important; }
```
