### ISSUE TITLE
Enable Drag Move for the URL bar

### ISSUE THREAD

**Issue by xmha97** [MrOtherGuy/firefox-csshacks#173]
Hi, how I can enable drag move for the URL bar?

https://user-images.githubusercontent.com/23485114/154179241-2b23b63c-ebe4-42cc-80cf-1e6d524c4fc1.mp4

My current CSS code (not working):
```css
#navigator-toolbox:active #urlbar {
pointer-events: auto;
}

#main-window:not(:active) #urlbar {
pointer-events: none !important;
}
```
