### ISSUE TITLE
Help with numbered texts

### ISSUE THREAD

**Issue by iDCoded** [MrOtherGuy/firefox-csshacks#177]
I am trying to customize the numbered tabs in such a way that the numbers only display when hovering over the tab.

**Comment by MrOtherGuy** [comment]
Change `.tab-text::before` to `.tabbrowser-tab:hover .tab-text::before`

I'm pretty sure it would work just like that.

**Comment by iDCoded** [comment]
This is what I had done, but the problem that I am facing is that, now all the tabs show '1'.
Every tab that I hover over, display '1'.

**Comment by MrOtherGuy** [comment]
Oh yeah, you are right. It would be like this instead:

```css
.tabbrowser-tab:first-child{ counter-reset: nth-tab 0 } /* Change to -1 for 0-indexing */
.tabbrowser-tab{ counter-increment: nth-tab }
.tabbrowser-tab:hover .tab-text::before{ content: counter(nth-tab) " "; }
```
