### ISSUE TITLE
What to add to navbar_below_content.css to get the bookmarks toolbar be below or above the urlbar?

### ISSUE THREAD

**Issue by Squaredude** [MrOtherGuy/firefox-csshacks#192]
I'm using the navbar_below_content.css script, but I would also like to get the bookmark toolbar be below the content (above the urlbar).

I'm not sure if we can make requests. I don't know how to modify this type of CSS by myself.

**Comment by MrOtherGuy** [comment]
This might be quite complicated using nav-bar below content. I think it will be easier to use toolbars_below_content.css as a base, and then add some custom rules to that to move tabs and menubar to top.

I'll get back to you later on how to do that exactly.

**Comment by Squaredude** [comment]
Thanks a lot for replying so quickly!

I hadn't seen that other file. I already made the switch in preparation. And yeah, it looks way more like what I want.

**Comment by MrOtherGuy** [comment]
Yeah, so I think you could just use that other file and then add this bit to the end:

```css
#browser,
#customization-container{
  padding-top: calc(var(--tab-min-height) + 2 * var(--tab-block-margin));
}
#titlebar{
  position: fixed !important;
  display: flex;
  flex-direction: column;
  top: 0;
  width: 100vw;
}
#toolbar-menubar{
  position: relative;
}
:root[sizemode="fullscreen"] #fullscr-toggler::after{
  content: "";
  display: block;
  transform: translateY(-100vh);
  height: 2px;
  z-index: 2000;
  width: 100vw;
}
#titlebar > .browser-toolbar{
  width: 100%;
}
#titlebar .titlebar-buttonbox-container{
  display: revert;
}
```

Toggling menubar is kind of awkward and here I assume you don't have menubar permanently enabled. If you want that then that would require a bit tweaking. I don't think it's possible to make that work well such it automatically would handle enabled and disabled menubar. Using navbar_below_content.css as a base would work for that, but that brings other issues so...
