### ISSUE TITLE
status_inside_urlbar: Hovered URL does not fit in URL bar less wide monitors

### ISSUE THREAD

**Issue by megamorphg** [MrOtherGuy/firefox-csshacks#205]
On my less wide monitor the URL bar is very short. Thus, the hovered URL does not fit.
Is it possible to still display the hovered URL in the URL bar as well as the bottom status area always?
I think that would be a good enough backup in case of URL issues.
Additionally, it would be great to have it wrap.

**Comment by MrOtherGuy** [comment]
Wrapping won't be possible.

What could be done though is that if window width is narrow enough, then in that case we would also show the normal statusbar. Or only show normal statusbar - whichever would be preferable.

**Comment by MrOtherGuy** [comment]
Well, you can "un-hide" the actual statusbar by adding `#statuspanel{ z-index: auto }` after that style.

But it is necessary to restyle the actual statusbar for the the style to work properly, so it won't look quite normal (it has bigger empty box around it).

**Comment by MrOtherGuy** [comment]
The thing is that if you style the actual statusbar then it will also affect the status in urlbar.

The status shown in urlbar is essentially just an *image* of the actual statusbar that covers the urlbar text, so if the actual statusbar style changes, then so does the image.

**Comment by MrOtherGuy** [comment]
> @MrOtherGuy is it just me or does the [centered_top_statuspanel](https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/centered_top_statuspanel.css) not move to top? I see the status is centered but at the bottom.
> 
> I can open a new issue for it.

Seems to be at top center for me as intended. (Firefox 105 on Win10)

**Comment by MrOtherGuy** [comment]
It's extremely rare that the style system treats CSS wrong. It's much much more likely that your style rules just don't have the effect you expect to have - ie. your custom style rules are "wrong".

But if I understand you correctly you are now trying to have the normal statuspanel at the top instead of bottom, yes? If so, then you should be able to apply this:

```css
#tabbrowser-tabpanels .browserContainer{ -moz-box-direction: reverse !important }
#tabbrowser-tabpanels .browserContainer > notificationbox{ -moz-box-ordinal-group: 2 }
#statuspanel{ margin-top: -16px !important; }
```

Just modify the negative top margin such that it aligns nicely to toolbars.

**Comment by MrOtherGuy** [comment]
Yeah, statusbar saw some changes recently. From 106 you can use more simple rule like this:

```css
#statuspanel{
  top: 0;
  padding-block: 0 2em !important;
}
```
