### ISSUE TITLE
hide_tabs_with_one_tab remove newtab button hover css

### ISSUE THREAD

**Issue by Anarky** [MrOtherGuy/firefox-csshacks#207]
Hello, with a `chrome` folder with only `hide_tabs_with_one_tab.css` imported, the new tab button lose its style (a grey box) when it is hovered.

**Comment by MrOtherGuy** [comment]
What Firefox version you use and what OS do you have?

This seems to work fine with Firefox 105 on Windows 10.

**Comment by Anarky** [comment]
I'm using Firefox 105 on Linux.

I tried to modify it, if I remove the `/* Button re-styling */` block the styling reappears on hover, but of course it prevents to hide the tabs bar completely:
![fx](https://user-images.githubusercontent.com/6974775/192105365-c5d0556b-df57-453d-b5f1-20d78519ba29.png)

I tried to add this but for some reason it doesn't work:
```css
.tabbrowser-tab[first-visible-tab="true"][last-visible-tab="true"] #tabs-newtab-button{
  visibility: collapse !important;
}
```

**Comment by MrOtherGuy** [comment]
Try:

```css
.tabbrowser-tab[first-visible-tab="true"][last-visible-tab="true"] ~ #tabs-newtab-button{
  visibility: collapse !important;
}

```
