### ISSUE TITLE
Is it possible to add autohide feature to vertical_bookmarks_toolbar.css?

### ISSUE THREAD

**Issue by sahinakkayadev** [MrOtherGuy/firefox-csshacks#217]
I am using `vertical_bookmarks_toolbar.css` and I wonder if it is possible to hide the toolbar when mouse is not over it? Currently it looks like this:
![normal](https://user-images.githubusercontent.com/32161460/197242471-d0fe90ce-50c5-4b33-a0d7-c326b2eb0b79.png)

It would be superb if we could autohide the left panel.

**Comment by MrOtherGuy** [comment]
Well, yes I suppose. You could add:

```css
#browser{ --uc-vertical-toolbar-width: 0 }
#PersonalToolbar{
  transition: transform 200ms ease-in-out 500ms;
  transform: rotateY(85deg);
  transform-origin: left;
  z-index: 2;
}
#PersonalToolbar:hover{
  transition-delay: 0ms;
  transform: rotateY(0deg);
}
```

Just edit that `85deg` to a value that results in the toolbar still being hoverable your system.
