### ISSUE TITLE
Use :has for better image document selector

### ISSUE THREAD

**Issue by Kyuuhachi** [MrOtherGuy/firefox-csshacks#222]
Instead of matching on a regex with specific file extensions, match anything that loads `resource://content-accessible/TopLevelImageDocument.css`:
```css
:root:has(head > link[rel=stylesheet][href="resource://content-accessible/TopLevelImageDocument.css"]) img.transparent {
  background: none;
}
```
