### ISSUE TITLE
Tab separator doesn't disappear correctly on last pinned tab (when hovered)

### ISSUE THREAD

**Issue by AndhikaWB** [MrOtherGuy/firefox-csshacks#246]
I'm using `tab_separator_lines.css`. Both separators (before and after the tab) will disappear when the last pinned tab is selected, but when only hovered, only the first (before tab) separator is disappeared, the last separator is not affected. See video for more detail.

https://user-images.githubusercontent.com/17119394/212461719-8689d9da-02e8-4e53-b2c1-ba4fec6fbe50.mp4

As for the gap between pinned and unpinned tabs, I remove it using the following code (before is 7px):
``` css
#tabbrowser-tabs[haspinnedtabs]:not([positionpinnedtabs]) > #tabbrowser-arrowscrollbox > .tabbrowser-tab[first-visible-unpinned-tab] {
  margin-inline-start: 0 !important;
}
```

Tested also with only `tab_separator_lines.css` style activated and there is no difference (the bug is still there).
