### ISSUE TITLE
Bars autohide when hovering over drop-down menus originating within them

### ISSUE THREAD

**Issue by J-Kappes** [MrOtherGuy/firefox-csshacks#255]
When using the autohide main toolbar stylesheet, clicking on the hamburger menu and then hovering over the resulting drop-down menu, the toolbar will eventually hide and the drop-down menu will slide up which can cause you to missclick items.

Would it be possible (and preferable) to suppress the autohide while hovering over any drop-down menus originating in the bar in question?

**Comment by MrOtherGuy** [comment]
Yes, it would certainly be preferable, but sadly we can't do that. Well, we *can* but as a side-effect the toolbars would show when *almost any* panel or menupopup is hovered. Like, toolbars would show up when you hover over website context menu.

You can add this ruelset if you want to try how that goes:

```css
#mainPopupSet:hover ~ box .browser-toolbar{
  transform: translateY(0);
  opacity: 1;
  transition-duration: 500ms, 200ms !important;
  transition-delay: 0s !important;
}
```
