### ISSUE TITLE
non_floating_sharp_tabs.css Firefox 110 active tab still shows bottom line

### ISSUE THREAD

**Issue by Dunedan** [MrOtherGuy/firefox-csshacks#261]
This is the same report as #258, but even though it got closed, I still encounter this bug.

Here is what a clean profile looks like for me with the latest version of `non_floating_sharp_tabs.css` enabled in Firefox 110:

![firefox-110-active-tab-bottom](https://user-images.githubusercontent.com/1735355/222414239-b2f236b5-f534-4bff-bdca-b8f3f3d05c62.png)

**Comment by MrOtherGuy** [comment]
One thing I can think of that would cause this is if you use Firefox default theme but have removed toolbar background-color like this:

```css
:root{
  --toolbar-bgcolor: transparent !important;
}
```

Then there isn't any color covering the line. If *you* have not added such custom rule then maybe your distro version of Firefox is doing that. In such case you can potentially fix it by adding:

```css
:root{
  --toolbar-bgcolor: #f1f2f3 !important;
}
```
