### ISSUE TITLE
Multi-row tabs below content / bookmarks toolbar problem.

### ISSUE THREAD

**Issue by ZorisBube** [MrOtherGuy/firefox-csshacks#269]
Hi,
I've been using your "tabs below content.css" codes for years. They are great, thanks for that. 

Today i tried to use "multi-row tabs below content.css" for the first time, also with the boolean pref to enable static menu bar. 
But my bookmarks toolbar also placed below the tabs, i mean at the very bottom. Is there a way to fix it and place it just below the url bar as it's before? (URL or the navigation bar.. I don't know how to name it)  

Also  i would like to ask another question.. When using "tabs below content.css"  with "autohide_bookmarks_toolbar.css" , bookmarks  appear in two ways. When hovering to the top navigation bar and when hovering the tabs which are placed below content. Is it possible to prevent bookmarks popping up when hovering over tabs?

Ver. 111.0.1 

Thanks and best regards...

**Comment by MrOtherGuy** [comment]
This is somewhat complicated. It should be possible, and you can try it out with something like this:

```css
@-moz-document url(chrome://browser/content/browser.xhtml){
  :root{
    --multirow-top-bookmarks-height: 28px;
  }
  #customization-container,
  :root:not([inFullscreen]) #content-deck,
  :root:not([inFullscreen]) #browser{
    margin-top: calc(var(--multirow-toolbar-height) + var(--multirow-top-padding) + var(--multirow-top-bookmarks-height) + var(--multirow-menubar-height,0px));
  }
  #PersonalToolbar{
    position: fixed;
    top: calc(var(--multirow-toolbar-height) + var(--multirow-top-padding) + var(--multirow-menubar-height,0px));
    width: 100vw;
  }
}
```

But there are problems: such that you need to explicitly set height for it - the 28px would depend on used font, font size on your platform, whether or not there are other buttons in the bookmarks toolbar etc. And it doesn't support autohiding - nor the setting to only show bookmarks toolbar on new tabs. I mean, the toolbar should hide just fine - but it will still continue to reserve space above the web-content area. On the other hand, if you want a bookmarks toolbar that never reserves space above web-content (like with autohide_bookmarks_toolbar.css) then that should be simpler.
