### ISSUE TITLE
tabs_below_content not compatible with navbar_tabs_oneliner

### ISSUE THREAD

**Issue by pmaziere** [MrOtherGuy/firefox-csshacks#27]
FF72.0 here.

While using navbar_tabs_oneliner alone is working fine, appending tabs_below_content , does not 
give the expected result, i.e. the navbar-tab-oneliner below the page content.
Instead I can see the tabs below the page content, but the oneliner remaining is kept above.

I guess tabs_below_content was not designed to embed the navbar with the tabs, which is the reason my expectation is not fulfilled. 

Would there be a way to have a mix of these two snippets working together as I expect ?

Thanks

**Comment by MrOtherGuy** [comment]
I think the best way to go about this would be not to try to combine these two, but to write one that does both. 

The hard thing with any toolbar below content is that you'll basically have to know how many toolbars there are below content.

**Comment by pmaziere** [comment]
Step by steps I managed to reach this solution, but it should be tested by others in order to check that it does not left any use case on the side of the road:

```css

@import url("/path/to/firefox-csshacks/chrome/window_control_placeholder_support.css");
@import url("/path/to/firefox-csshacks/chrome/linux_gtk_window_control_patch.css");
@import url("/path/to/firefox-csshacks/chrome/urlbar_full_width.css");
@import url("/path/to/firefox-csshacks/chrome/navbar_tabs_oneliner.css");
@import url("/path/to/firefox-csshacks/chrome/tabs_below_content.css");

#navigator-toolbox,#TabsToolbar,#PersonalToolbar{position: fixed !important; bottom: 0; display: block; z-index:100 } 
#nav-bar,#TabsToolbar{vertical-align: bottom !important;}
#TabsToolbar-customization-target, #nav-bar-customization-target{ width: 100vw}
:root:not([inDOMFullscreen]) #browser{ margin-bottom: var(--tab-min-height) }

/* Not required, but I prefer having the menu icon on the left */
#PanelUI-button,
#customization-panel-container,
#customization-panelWrapper .panel-arrow {
  -moz-box-ordinal-group: 0 !important;
}
```
This way, it does use existing hacks and only adds what is required for this specific case.
