### ISSUE TITLE
hide tabs toolbar without window controls

### ISSUE THREAD

**Issue by AntDavidLima** [MrOtherGuy/firefox-csshacks#271]
Hello!

I saw that there are styles `hide_tabs_with_one_tab.css` and `hide_tabs_with_one_tab_w_window_controls.css` and I understand why, but I think there should also be `hide_tabs_toolbar.css` and `hide_tabs_toolbar_w_window_controls.css`, for people who want to hide tabs and don't want to use `window_control_placeholder_support.css`, as they don't even use those controls, just keyboard shortcuts.

If you think it makes sense, please implement it, I couldn't identify the style that does this, I'm horrible with css.

Thank you for your attention.

**Comment by MrOtherGuy** [comment]
I don't think a style for that makes a whole lot of sense since it is so trivial. It would be simply:

```css
#titlebar{ appearance: none !important }
#TabsToolbar{ visibility: collapse }
```

And the first line probably doesn't even need to be there on non-Windows systems - or if you enable menubar or native titlebar.

**Comment by AntDavidLima** [comment]
Here in my browser this style doesn't hide the window controls, and with the menubar or nativebar active, I still end up with an extra bar at the top. My goal was to have no slash at all, but I achieved this with the following style:

```css
 :root[tabsintitlebar] #toolbar-menubar[autohide="true"]{
   min-height: unset !important;
+   height: 0 !important;
+   margin-bottom: 40px;
   position: relative;
 }

- :root[sizemode="fullscreen"] #TabsToolbar > :is(#window-controls,.titlebar-buttonbox-container){
-   visibility: visible !important;
-   z-index: 2;
- }
```
