### ISSUE TITLE
@import doesn't work with online URLs?

### ISSUE THREAD

**Issue by Cleridwen** [MrOtherGuy/firefox-csshacks#304]
hi!

sorry if this isn't a good place to ask for help… I haven't found answers online.
for some reasons, using `@import` to point directly to the online file doesn't work in `userChrome.css`. is this intended? is there a way to change it? or am I doing something wrong?
```css
@import url(http://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/combined_favicon_and_tab_close_button.css);
@namespace url(http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul);

/*** Remove items from image context menu ***/

/* Email Image... */
#context-sendimage {
  display: none !important;
}

/* Set Image as Desktop Background... (and preceding separator) */
#context-sep-setbackground, #context-setDesktopBackground {
  display: none !important;
}

/* Inspect Accessibility Properties */
#context-inspect-a11y {
  display: none !important;
}

/* Save Page to Pocket */
#context-pocket { 
  display: none !important; 
}
```
I tried using https, adding or removing `"`s around the url.
considering Firefox requires a restart every time anything is changed, I assume that loading content from online sources would introduce some delay that would make things simply not work. but in case there's any other way…
