### ISSUE TITLE
Is there any css to differentiate loaded tabs from unloaded?

### ISSUE THREAD

**Issue by scmanjarrez** [MrOtherGuy/firefox-csshacks#310]
I meant, to have a grayed out tabs that haven't been loaded yet (you click it, then it refresh and web content)

**Comment by MrOtherGuy** [comment]
For that you can simply use something like this:

```css
.tabbrowser-tab[pending]{
  opacity: 0.4;
}
```
