### ISSUE TITLE
Misalignment using urlbar_results_in_two_rows in Firefox 122

### ISSUE THREAD

**Issue by Dupond** [MrOtherGuy/firefox-csshacks#336]
Hello!

Since the release of Firefox 122, the urlbar_results_in_two_rows code no longer works: in the address bar results, the item name is no longer aligned horizontally with the url, and the icon is no longer centered vertically.

Is there any way of solving these problems?

Many thanks in advance!

**Comment by MrOtherGuy** [comment]
Yeah, 369c384 fixes the alignment issue. I don't think the icon has ever been centered vertically though. At least it isn't when trying the style in ESR 115.

**Comment by MrOtherGuy** [comment]
If you wanted to also vertically align it then I suppose you could add something like this:

```css
.urlbarView-row[has-url]:not([type="switchtab"]) .urlbarView-favicon,
.urlbarView-row[has-url]:not([type="switchtab"]) .urlbarView-type-icon{
  transform: translateY(8px)
}
```

But honestly I don't think that looks as nice as having the icon be aligned to the title.
