### ISSUE TITLE
non_floating_sharp_tabs.css: opacity changes remain

### ISSUE THREAD

**Issue by Dupond** [MrOtherGuy/firefox-csshacks#338]
Hello!

On Firefox 122 (under Arch Linux), despite a2b52b6, the titlebar becomes slightly lighter when the Firefox window loses focus.

Would you have any idea to prevent that? Thank you for all your amazing css!

**Comment by MrOtherGuy** [comment]
What exactly do you mean by "titlebar"? If you mean the actual native titlebar then you OS is drawing that and there's nothing we can do to change it.

If on the other hand native titlebar is disabled and you mean simply the "area behind tabs and/or menubar" then yes, it can have different background-color when window is not focused. This can be defined in your theme and we do not want to change that. But you can of course change it for yourself by adding something like this:

```css
#navigator-toolbox{ background-color: ActiveCaption !important }
#navigator-toolbox:-moz-lwtheme{ background-color: var(--lwt-accent-color) !important }
```

That should force the "active window background-color" per your theme to be used whether the window is active or not.
