### ISSUE TITLE
autohide toolbar: bigger hover area

### ISSUE THREAD

**Issue by musjj** [MrOtherGuy/firefox-csshacks#345]
Is there a way to make it so that the hover area is bigger, so that you can more easily reveal the toolbar?

I often find myself "overshooting" just so that the hover event is triggered, which is kind of inefficient in terms of mouse movement.

**Comment by MrOtherGuy** [comment]
If you mean autohide_toolbox.css, then you can simply make the `--uc-toolbox-rotation` variable smaller. Line 11 controls normal windows, and line 15 is for maximized ones.

**Comment by musjj** [comment]
How about `autohide_bookmarks_and_main_toolbars.css`?

**Comment by MrOtherGuy** [comment]
That style should show the main toolbar and bookmarks toolbar whenever your cursor is hovering tabs toolbar or menubar. Is your intention that you would want toolbars to also show up if the cursor is somewhere *nearby* tabs toolbar or what? Doing that should be possible, but it would prevent you from interacting with top portion of web pages.

**Comment by MrOtherGuy** [comment]
For that you'll need something more complicated to have it look okay.
This should work if you add it to the end of the style:

```css
:root[sessionrestored] #navigator-toolbox > .browser-toolbar{
  opacity: 0;
  transform: rotateX(70deg);
  transition-property: transform, opacity !important;
}
#mainPopupSet:has(> #appMenu-popup:hover) ~ #navigator-toolbox > .browser-toolbar,
:root[sessionrestored] #navigator-toolbox:is(:focus-within,:hover) > .browser-toolbar{
 opacity: 1; 
 transform: rotateX(0deg);
}
```

**Comment by musjj** [comment]
Thank you, this works great! This also means that I can reduce the padding of the tab bar, to save even more space:

```css
#navigator-toolbox {
  --uc-navbar-height: -48px !important;
}
```

Btw, what value should I tweak to control the size of the hover area?
