### ISSUE TITLE
New csshack -- more visible notification dot in pinned tabs (email, chat, etc)

### ISSUE THREAD

**Issue by jotaf98** [MrOtherGuy/firefox-csshacks#347]
Hi, first of all thanks for this, the autohide_toolbox.css is amazingly well done!

Not sure if you're taking submissions, but I thought I'd put in a quick one, in case it interests anyone. I'm pasting it here instead of creating a PR because I'm not sure if you actually want it and also not sure about the style guidelines; I figured that if you want to include it, you probably have your own preferences as to how best to format it.

Often one has pinned tabs with "web apps" that have notifications -- email, chat, etc. Unfortunately, the current way in which notifications are displayed is not very visible in the default theme. This simply changes them to a small (but quite visible) red dot, similar to those used in Slack. It uses CSS variables so the dot is customizable (size and color).

```css
/* Make the "title changed" notification dot on pinned tabs red */
.tabbrowser-tab > .tab-stack > .tab-content[pinned][titlechanged]:not([selected="true"]) {
    --tab-attention-icon-color: #ff3b6b;  /* default #2ac3a2 */
    --tab-attention-icon-size: 3px;  /* default 2px */

    background-image: radial-gradient(circle, var(--tab-attention-icon-color), var(--tab-attention-icon-color) var(--tab-attention-icon-size), transparent var(--tab-attention-icon-size)) !important;

    background-position: center bottom calc(6.5px - var(--tab-attention-icon-size) + var(--tabs-navbar-shadow-size)) !important;

    background-size: calc(2 * var(--tab-attention-icon-size) + 1px) calc(2 * var(--tab-attention-icon-size) + 1px) !important;
}
```
