### ISSUE TITLE
firefox multi row space and window button placement

### ISSUE THREAD

**Issue by RashiqAzhan** [MrOtherGuy/firefox-csshacks#348]
![image](https://github.com/MrOtherGuy/firefox-csshacks/assets/7370540/31eefa1e-83fb-46f8-960c-72fec8e30a58)

Is there a way to better utilize the space boxed in aquamarine? Maybe have the tabs push into them more?

Is it possible to move the window controls (orange) to the bottom right side in the empty space on the toolbar?

Is there a way to push the toolbar to utilize all the space on the left (energy green)?

I'm using the git method with the latest commit on the master branch.
userChome.css
```css
@import url(chrome/multi-row_tabs_window_control_patch.css);
@import url(chrome/tab_close_button_always_on_hover.css);
@import url(chrome/tab_loading_progress_throbber.css);
@import url(chrome/button_effect_scale_onclick.css);
@import url(chrome/autohide_menubar.css);
@import url(chrome/hide_toolbox_top_bottom_borders.css);
@import url(chrome/vertical_context_navigation.css);
@import url(chrome/minimal_popup_scrollbars.css);
@import url(chrome/dark_context_menus.css);
@import url(chrome/dark_additional_windows.css);
@import url(chrome/dark_checkboxes_and_radios.css);
@import url(chrome/urlbar_centered_text.css);
@import url(chrome/window_control_placeholder_support.css);
@import url(chrome/multi-row_tabs.css);
@import url(chrome/urlbar_popup_full_width.css);
@import url(chrome/compact_extensions_panel.css);
@import url(chrome/iconized_main_menu.css);
@import url(chrome/privatemode_indicator_as_menu_button.css);
@import url(chrome/minimal_in-UI_scrollbars.css);
@import url(chrome/loading_indicator_bouncing_line.css);

:root{
  --toolbar-bgcolor: rgb(36,44,59) !important;
  --uc-menu-bkgnd: var(--toolbar-bgcolor);
  --arrowpanel-background: var(--toolbar-bgcolor) !important;
  --autocomplete-popup-background: var(--toolbar-bgcolor) !important;
  --uc-menu-disabled: rgb(90,90,90) !important;
  --lwt-toolbar-field-focus: rgb(36,44,59) !important;
  --multirow-n-rows: 20; 
  --multirow-tab-dynamic-width: 1; 
}

#sidebar-box{ --sidebar-background-color: var(--toolbar-bgcolor) !important; }
window.sidebar-panel{ --lwt-sidebar-background-color: rgb(36,44,59) !important; }

#toolbar-menubar{
  height: 30px;
}
```

Love your work. You're making Firefox bearable again.
