### ISSUE TITLE
Icons overlap in narrow window with tabs toolbar hidden

### ISSUE THREAD

**Issue by dekatr0n** [MrOtherGuy/firefox-csshacks#386]
I'm using `window_control_placeholder_support.css` together with `hide_tabs_toolbar.css`, but I noticed that it does not handle narrow window widths very well. The application menu icon overlaps with the other icons and url bar when the window becomes too small. I'm using Windows 10.

Normal window:
![Screenshot 2024-07-19 200517](https://github.com/user-attachments/assets/7628cfb9-9f5b-4eb0-8348-5ae065d4ed61)

Narrow window:
![Screenshot 2024-07-19 200501](https://github.com/user-attachments/assets/d971908d-8c7c-4c79-9e8d-8cd4fa61d0c3)
![Screenshot 2024-07-19 200438](https://github.com/user-attachments/assets/7e543d82-339f-48db-8191-4a6d70dca428)

**Comment by MrOtherGuy** [comment]
Yeah, this is sort of annoying, but I'm not sure what a good behavior would be. We *could* let urlbar get narrower than the current limit and it would *look* more neat but I don't think it's sane to have urlbar be unusably narrow. We cannot make Firefox push navigation buttons to overflow menu either, and we don't want to hide them as they are rather crucial part of the UI, same applies to window controls.

There just isn't enough space in narrow windows to show everything. What would be a good behavior in your opinion?

**Comment by dekatr0n** [comment]
I've replaced this code in `window_control_placeholder_support.css`
```
#nav-bar {
  border-inline: var(--uc-window-drag-space-pre,0px) solid transparent;
  border-inline-style: solid !important;
  border-right-width: calc(var(--uc-window-control-width,0px) + var(--uc-window-drag-space-post,0px));
  background-clip: border-box !important;
}
```
with the following
```
#nav-bar {
  padding-left: var(--uc-window-drag-space-pre,0px) !important;
  padding-right: calc(var(--uc-window-control-width,0px) + var(--uc-window-drag-space-post,0px)) !important;;
}
```
and noticed that it somewhat helps. The layout still overlaps at narrow widths, but the width at which it overlaps is decreased. Now, it doesn't overlap when tiling a window to one half of my screen (1080p, 125% scaling), which is an improvement for me.

About good behaviour for narrow widths, I couldn't really think of a good solution. For reference, I noticed that MS Edge hides the navigation icons when the window is too narrow. Another thing one could do is to reintroduce a (thin) title bar at the top at narrow widths to accommodate the window controls, like Firefox Nightly with vertical tabs enabled, but I don't know if this is a good solution.
![image](https://github.com/user-attachments/assets/89a51bfd-1ce1-4c25-9ed3-9f0c8b46ca5d)

**Comment by MrOtherGuy** [comment]
This requires some thought. I know that using padding instead of border makes intuitively more sense, but I know there is some very specific reason for why we use border - I just cannot recall off the top of my head what that reason is. There's also a chance that the issue with using padding isn't relevant any more.

Even so, switching to using padding requires me to test a lot of styles and interactions so I'm not able to change that without some careful testing which would take some time.

I would be glad if we can switch to using padding though.

**Comment by datguypiko** [comment]
> This requires some thought..

What are your thoughts on just using flex for dealing with oneliner. It avoids most of these issues. The only thing I didnt bother fixing was secondary menu bar (alt) (#toolbar-menubar) as I dont use it ever, which can be fixed with just making it absolute and moving above all of them. 

```css
@media (min-width:1000px) {
  #navigator-toolbox { display: flex; flex-wrap: wrap; flex-direction: row; }

  #nav-bar {
    order: 1;
    flex:fit-content;
    flex-grow: 1.5; 
  }
  
  #nav-bar #urlbar-container { 
    min-width: 260px !important; 
    width: auto !important; 
  }

  #titlebar {
    order: 2;
    flex:fit-content;
    flex-grow: 8;
  }

  #PersonalToolbar { order: 3; width: 100%;}
  
}
/* Fixes oneliner in customization view */
#customization-panelWrapper > .panel-arrowbox > .panel-arrow{ margin-inline-end: initial !important; }
```




</br>
</br>
Or this one with setting custom width more accurately yourself.


```css
:root {
   --uc-urlbar-min-width: 45vw;
   --uc-urlbar-max-width: 45vw;
}

@media (min-width:1100px) {

  #navigator-toolbox { display: flex; flex-wrap: wrap; flex-direction: row; }

  #nav-bar {
    order: 1;
    width: var(--uc-urlbar-min-width);
  }
  
  #nav-bar #urlbar-container { min-width: unset !important; width: auto !important; }

  #titlebar {
    order: 2;
    width: calc(100vw - var(--uc-urlbar-min-width) - 1px);
  }
  
  #PersonalToolbar {
    order: 3;
    width: 100%;
  }
  
  #navigator-toolbox:focus-within {
    & #nav-bar { 
      width: var(--uc-urlbar-max-width); 
    }
    
    & #titlebar { 
      width: calc(100vw - var(--uc-urlbar-max-width) - 1px); 
    } 
  }
 
}

/* Fixes oneliner in customization view */
#customization-panelWrapper > .panel-arrowbox > .panel-arrow{ margin-inline-end: initial !important; }
 
```
