### ISSUE TITLE
One weird bug with "window_control_placeholder_support.css"

### ISSUE THREAD

**Issue by datguypiko** [MrOtherGuy/firefox-csshacks#388]
(windows11) I was trying to fix my window control buttons being on top of sidebar in fullscreen (F11) ([issue](https://github.com/datguypiko/Firefox-Mod-Blur/issues/136)) when sidebar is on the same side. So I found this line of code in your file that fixed it `:root[sizemode="fullscreen"] #navigator-toolbox { position: relative; }`

Now with this code it created this weird bookmarks bar bug where overflow appears and stays when you toggle to Fullscreen (F11) or fullscreen video mode.

I removed all my code and just copy pasted window_control_placeholder_support.css and I reproduced the same thing.
![image](https://github.com/user-attachments/assets/7fce4e4c-8cb4-4a87-b4d0-979ad56bfb3e)

The problem with that line of code that it conflicts with setting "absolute" on control buttons.
Anyway to fix this conflict? The only solution was to not use absolute in fullscreen(F11) but then it doesnt stay at the position you want.

<br>
And wanted to ask one more question, what is ID element #window-controls used for? Is it for different operating system, I couldnt find anything in inspect tools.

**Comment by MrOtherGuy** [comment]
Well, that's definitely weird. I can safely say that I don't have a clue about why that happens, because it can be reproduced with simply this:

```css
:root[sizemode="fullscreen"] #navigator-toolbox { position: relative; }
:root[sizemode="fullscreen"] #TabsToolbar > .titlebar-buttonbox-container:last-child{
  position: absolute;
  display: flex;
  top: 0;
  right:0;
  height: 40px;
}
```

As soon as `.titlebar-buttonbox-container` is set to have position absolute, the issue start to happen. I have no idea how the titlebar-buttonbox would affect the overflow button, it doesn't make any sense.

`#window-controls` however, that's just a leftover from old Firefox versions. Some time back the fullscreen mode had a separate set of titlebar-buttons with that id. I could clean those up because Firefox doesn't seem to use them anywhere anymore.

**Comment by datguypiko** [comment]
One thing that fixes it is not using `:root[sizemode="fullscreen"]` and just setting 
```css
#navigator-toolbox { position: relative; }
```
or 
```css
:root[sizemode="fullscreen"] #navigator-toolbox { position: relative; }
#navigator-toolbox { position: initial !important; }
```

You think any of these can cause other issues?
