### ISSUE TITLE
window_control_placeholder_support + hide_tabs_with_one_tab_w_window_controls

### ISSUE THREAD

**Issue by sdsucks** [MrOtherGuy/firefox-csshacks#413]
i've been using these two codes together to make the navbar+urlbar+toolbar+window.control into one line.

it seems broken after updating my nightly yesterday.

now it looks like this.

the codes are up to date.

![window control buttons](https://github.com/user-attachments/assets/ecf6e482-aaa0-406f-a7b1-a0386a1c2e3d)

**Comment by MrOtherGuy** [comment]
Sweet! The one change I was waiting to eventually happen has finally landed. A **lot** of my styles are very likely to need to be changed but now that `#titlebar` container has been removed it makes certain things much simpler than they were before.

Only downside is that keeping compatibility with ESR128 can be kinda complicated.

**Comment by Tijs-B** [comment]
A similar issue appears with `window_control_placeholder_support` + `hide_tabs_toolbar_osx`, that combination looks like this:

![screenshot](https://github.com/user-attachments/assets/1fd72222-0a37-4010-999f-cd7956b40faf)

Firefox Nightly 133.0a1 (2024-10-03) on macOS Sonoma 14.4

**Comment by MrOtherGuy** [comment]
Yeah, probably. There's at least 35 styles that will have issues regarding recent changes. Many of those could now be rewritten to be much simpler so I'll need to think how to do things. Chances are that I'm gonna write new styles that work with Firefox 133 and let the old ones be as is.

**Comment by MrOtherGuy** [comment]
@Tijs-B  This isn't going to help hiding tabs if only one tab is visible, but since you sound to be using macOS would check how this works:

```css
@media (-moz-bool-pref: "sidebar.verticalTabs"){
  #sidebar-main{
    visibility: collapse;
  }
}
@media not (-moz-bool-pref: "sidebar.verticalTabs"){
  #TabsToolbar{
    visibility: collapse;
  }
  :root[sizemode="fullscreen"] #nav-bar > .titlebar-buttonbox-container{
    display: flex !important;
  }
  :root[tabsintitlebar] #toolbar-menubar[autohide="true"] ~ #nav-bar{
    & > .titlebar-buttonbox-container{
      display: flex !important;
    }
    :root[sizemode="normal"] & {
      & > .titlebar-spacer{
        display: flex !important;
      }
    }
    :root[sizemode="maximized"] & {
      & > .titlebar-spacer[type="post-tabs"]{
        display: flex !important;
      }
    }
  }
}
```

This is essentially the only thing you would need for hiding tabs toolbar - no more placeholder_support sheet and all the other weird hackery. This would just work whether or not one has menubar enabled, but I have a suspicion it doesn't work on macOS. I'm fairly certain I know what needs to be done instead on macOS but I would rather not do it if it could be avoided.

**Comment by Tijs-B** [comment]
That looks like this:

![afbeelding](https://github.com/user-attachments/assets/73dff4cf-4e95-42ca-8cb4-efe80a1da0cf)

The three buttons are gone now. I've got no experience in debugging these kinds of things, but if you want, I can look into it a bit deeper.

**Comment by MrOtherGuy** [comment]
Okay, that looks like what I expected... sad days. The solution is to duplicate most of the rules for macos, which is simple to do but it woul've been great to not need to do that.

**Comment by Tijs-B** [comment]
Alright, sucks. No hurry! Let me know if you need me to do anything. I've got no experience styling Firefox except for using this library, but I do have experience with CSS.

**Comment by Tijs-B** [comment]
That seems to work for the normal window modes, but not for full screen. The screenshots:

Resized to a pretty small window: 
![afbeelding](https://github.com/user-attachments/assets/0c476e19-e8a8-48d5-8963-663a2f0aee43)

Maximized to use the full screen size (if that's what you mean by maximized window mode?):
![afbeelding](https://github.com/user-attachments/assets/de576f1b-c394-4227-a0ab-fe4e4a69fab3)

Full screen:
![afbeelding](https://github.com/user-attachments/assets/72ef5252-dc34-4bfc-8d3b-b7422104f6d9)

Full screen, when moving the mouse completely to the top of the screen actually shows the buttons:
![afbeelding](https://github.com/user-attachments/assets/e802cb18-4a66-418f-a3e5-07d8f479510d)

Although I'm not sure if this has worked before the Firefox changes, with the old code, though. This may be on purpose, showing the buttons only when moving the mouse to the top of the screen to show the topmost bar macOS bar. (Though, on Pycharm which I happen to have open, the buttons are always shown in the top left).

**Comment by MrOtherGuy** [comment]
How does Firefox display window controls when fullscreen? Would it be expected to show them inside nav-bar or in that OS native bar thingy?

Also, maximized is kinda wrong as well. The empty space should be between window controls and first toolbar button, but now it's on the other side. That feels like we would need to write some separate rules depending on if the window controls are on left or right side anyway. And at that point might as well write separate ruleset for macos properly.

**Comment by Tijs-B** [comment]
> Also, maximized is kinda wrong as well. The empty space should be between window controls and first toolbar button, but now it's on the other side

I think that's because I have an "empty space" element on my bar: 
![afbeelding](https://github.com/user-attachments/assets/11d6a9a2-21a2-4cc9-96f0-454df21cba31)

**Comment by Tijs-B** [comment]
For completeness, with a fresh Firefox profile (Firefox Nightly 133.0a1 on macOS Sonoma 14.4), and with this in `userChrome.css`: 

```css
@media (-moz-bool-pref: "sidebar.verticalTabs") {
  #sidebar-main {
    visibility: collapse;
  }
}
@media not (-moz-bool-pref: "sidebar.verticalTabs") {
  #TabsToolbar {
    visibility: collapse;
  }
  :root[sizemode="fullscreen"] #nav-bar > .titlebar-buttonbox-container {
    display: flex !important;
  }
  :root[tabsintitlebar] #toolbar-menubar:not([autohide="false"]) ~ #nav-bar {
    & > .titlebar-buttonbox-container {
      display: flex !important;
    }
    :root[sizemode="normal"] & {
      & > .titlebar-spacer {
        display: flex !important;
      }
    }
    :root[sizemode="maximized"] & {
      & > .titlebar-spacer[type="post-tabs"] {
        display: flex !important;
      }
    }
  }
}
```

results in this:

- small window:  <img width="885" alt="afbeelding" src="https://github.com/user-attachments/assets/d404e6e9-c397-451a-aed7-b3c8473259ac">
- maximized window: (here indeed the space is gone to the right of the window buttons): <img width="1512" alt="afbeelding" src="https://github.com/user-attachments/assets/3eeae16a-137a-4ca8-a771-e496f4cea1f0">
- fullscreen: <img width="1512" alt="afbeelding" src="https://github.com/user-attachments/assets/cce99636-38be-48db-af3b-5e9d7177ee24">
- fullscreen, moving mouse to the top bar: 
<img width="1511" alt="afbeelding" src="https://github.com/user-attachments/assets/e3d0574c-65c5-434e-b7f3-628b82ead9bf">
