### ISSUE TITLE
[Request] Move the menubar from left side to right side

### ISSUE THREAD

**Issue by waffles38** [MrOtherGuy/firefox-csshacks#427]
Hello MrOtherGuy, love your work!

Was wondering if you could make a mod to move the menubar to right side like in the image? I really dislike having it on the left side so it would be great if you can create this. Thank you

<img width="1485" alt="firefox" src="https://github.com/user-attachments/assets/b40d6ee6-a959-4673-8b73-8910145b61f5">

**Comment by MrOtherGuy** [comment]
With Firefox 133 this becomes a bit more complicated but this should work:

```css
#navigator-toolbox{
  display: grid;
  grid-auto-columns: 1fr auto;
}
.browser-toolbar,
.global-notificationbox,
#tab-notification-deck{
  grid-column: 1/3;
}
#TabsToolbar{
  grid-row: 1/2;
  grid-column: 1/2;
}
#toolbar-menubar{
  grid-column: 2/3;
}
#toolbar-menubar > spacer{
  display: none;
}
#main-window #menubar-items > #main-menubar{
  flex-grow: 1;
}
```

Also with 133 you can move the alltabs button wherever you like in customize mode just like any other button.

**Comment by waffles38** [comment]
Thank you so much man! It works great and i am currently using v131.
I was wondering, is it possible to also add an empty space bar to the far right "before" the menubar? See my example image

<img width="1488" alt="ff" src="https://github.com/user-attachments/assets/3e0c2ef1-2cea-4424-ab96-a44f4e7f6a48">

**Comment by MrOtherGuy** [comment]
That doesn't look like it's supposed to look. Window controls are supposed to be in the right corner like they normally are. That probably means that you have some other styles that mess things up - and possibly also that you don't have menubar enabled.

If you then would want a space *between* menubar items and window-controls then you could simply add something like:

```css
#toolbar-menubar > spacer{ width: 40px }
```
