### ISSUE TITLE
Increaase size of bookmark toolbar icons

### ISSUE THREAD

**Issue by Bartholomew22** [MrOtherGuy/firefox-csshacks#430]
The bookmark icons are too small.  Using userChrome.css the space that icons occupy an be increased, but not the icons themselves. 
How can the icon be made larger?

**Comment by MrOtherGuy** [comment]
You can do this:

```css
.bookmark-item > .toolbarbutton-icon {
  width: 20px !important;
  height: 20px !important;
}
```

But images themselves are likely stored as 16x16, so the upscaling can cause them to look blurry.
