### ISSUE TITLE
navbar_below_content + autohide_toolbox

### ISSUE THREAD

**Issue by vredesbyyrd** [MrOtherGuy/firefox-csshacks#445]
Hi, I much appreciate you sharing these csshacks. 

Is there anyway to use `navbar_below_content.css` + `autohide_toolbox.css` together? My goal is to permanently hide the tabbar, and only show the navbar (at the bottom of the window) when it is focused (ctrl+l) or hovered.  I'll probably also disable the urlbar popout/dropdown menu as well. I'm going for something very minimal like luakit or qutebrowser.

When using them together, `autohide_toolbox.css` displays the navbar on top of the window, and leaves an empty bar (height of the navbar) at the bottom. 

I have been working on it for awhile but no luck thus far. Any pointers would be very appreciated! Thanks for your time.

**Comment by MrOtherGuy** [comment]
The behavior you are looking for should be possible, but I don't think that navbar_below_content + autohide_toolbox is the correct way to go. Instead, I think you should start with just toolbars_below_content, then add simply `#TabsToolbar{ visibility: collapse }` and you are almost there. Only thing remaining is to have nav-bar hide until hovered/focused which does require some thinking but it shouldn't be too bad.

**Comment by vredesbyyrd** [comment]
Somehow I overlooked `toolbars_below_content`. That plus `#TabsToolbar{ visibility: collapse }` does seem like a better starting point. 

I'll report back if I can figure out hiding it. Thanks :)

**Comment by vredesbyyrd** [comment]
So that hides the navbar, but the urlbar stays visible. I should have mentioned I am on firefox 133, so maybe thats why. 

I do not know enough to know if this is a good approach, but I did find a snippet that with some tweaking seems to work well.  Thanks again for the pointers!

```css
/* This requires Firefox 133 */

#navigator-toolbox{
  display: contents;
}
#main-window > body{
  > #browser,
  .global-notificationbox,
  #tab-notification-deck,
  #toolbar-menubar{
    order: -1;
  }
  #TabsToolbar{
    max-height: calc((var(--tab-min-height) + 2 * var(--tab-block-margin,0px)) * var(--multirow-n-rows,1));
  }
  #urlbar[breakout][breakout-extend]{
    display: flex !important;
    flex-direction: column-reverse !important;
    transform: translateY(calc(var(--urlbar-container-height) - 100%));
  }
  .urlbarView-body-inner{ border-top-style: none !important; }
}

/* completely hide tabbar, for now */
#TabsToolbar{ visibility: collapse }

/* Autohide navigation bar. */
:root[sessionrestored]:not([customizing]) #navigator-toolbox:not(:hover):not(:focus-within) #nav-bar {
    max-height: 0 !important;
    min-height: 0 !important;
    overflow: hidden;
    /*margin-bottom: 0px;
    opacity: 0; */
    /* Wait 500ms before hiding the nav bar on unfocus */
    transition: all 0.3s ease-in-out !important;
}

:root[sessionrestored] #nav-bar {
    /* Max height must be set to something here to be animated */
    max-height: 100px;
    min-height: 0;
    transition: all 0.3s ease-in-out !important;
}
```
