### ISSUE TITLE
"window_control_placeholder_support.css" causes window controls to be in top middle

### ISSUE THREAD

**Issue by aviadhaham** [MrOtherGuy/firefox-csshacks#469]
## Issue
After updating to Firefox 1.33, the issue started, the window controls, instead of being top left as always, they started being at the top, but in middle ("floating" over the URL bar in my case).

After debugging using the devtools, I found the issue is here, in the marked element:
![Issue Chronicle - How I Fixed the Firefox window controls out of order](https://github.com/user-attachments/assets/d8fc196d-dbd9-4e6b-94f4-50d7efa4087d)

## Solution

I took the latest version of the CSS file ([github](https://raw.githubusercontent.com/MrOtherGuy/firefox-csshacks/refs/heads/master/chrome/window_control_placeholder_support.css)), added the below CSS, **and it solved it**:

```css
/* To fix the weird position of the window controls from the middle to the left */
#TabsToolbar {
  justify-content: normal !important;
}
```

@MrOtherGuy If that's good for you, I can create a PR. I wanted to share first about the issue.
