### ISSUE TITLE
Enabling widget.windows.mica in about:config breaks hide_tabs_toolbar_v2.css

### ISSUE THREAD

**Issue by Hikandy** [MrOtherGuy/firefox-csshacks#474]
The windows maximize, minimize and close buttons disappear on using this CSS resulting in 
![image](https://github.com/user-attachments/assets/e2dbe8c0-c818-4aad-abe9-1c9175919179)

The buttons still work but they are invisible. Using Firefox 133

**Comment by MrOtherGuy** [comment]
I have no idea what that might be all about, especially if they do work. I also won't be able to test anything on Win11 so that might be kinda hard for me to fix.

**Comment by MrOtherGuy** [comment]
What happens if you added this:

```css
@media (-moz-windows-mica) {
  .titlebar-buttonbox{ opacity: 0 }
}
```
