### ISSUE TITLE
Firefox 133: "hide_tabs_toolbar" and "windows_control_placeholder_support" Not Displaying Minimize, Maximize, and Close Buttons

### ISSUE THREAD

**Issue by supervaka** [MrOtherGuy/firefox-csshacks#489]
EDIT: Resolved after reading https://github.com/MrOtherGuy/firefox-csshacks/issues/467#issuecomment-2508813251, but I guess I'll keep this issue for posterity.
Can this be documented either in the readme or  hide_tabs_toolbar.css + windows_control_placeholder_support.css?

.
.
.
Similar but different compared to #474
I did not touch `widget.windows.mica` (so it is `false`).
And I use v1, not `hide_tabs_toolbar_v2.css`

my `userChrome.css`(`git pull`'d 10 minutes ago):
```css
@import url(chrome/window_control_placeholder_support.css);
@import url(chrome/hide_tabs_toolbar.css);
```
![image](https://github.com/user-attachments/assets/51341a94-c2b3-4891-8b37-75174d0d15a6)
Nothing happens when I click on the empty space where the maximize, minimize and close buttons used to be

As mentioned in #474 when I set `sidebar.revamp` and `sidebar.verticalTabs` to true I see this:
![image](https://github.com/user-attachments/assets/1e83221a-37b3-4f5c-87d7-fac9031b0e95)
The buttons on the left change on hover and are functional
The buttons on the right do not change on hover, and they are not functional

I'm on Windows 11 using Firefox 133
Would it be useful to share my prefs.js? or any thing else?

**Comment by MrOtherGuy** [comment]
Yeah, considering the number of issues created about this I think it might be worth it to add a note to the old styles.

I kinda hoped I could handle this such that when ESR 128 cycle is over I would migrate "_v2" styles to the original file names. Alternatively I could migrate them right now and just rust move the original old files to deprecated folder. But I don't know how best to handle this honestly.

**Comment by MrOtherGuy** [comment]
Yes, window_control_placeholder_support.css only exisits for users of ESR 128 - otherwise I'd move it to deprecated.

**Comment by trallnag** [comment]
For me the windows controls are disappearing even with hide_tabs_toolbar_v2 and I am on Firefox 135 right now. Weird. My config is pretty small.

```css
@import url(chrome/bookmark_panel_enlarge.css);
@import url(chrome/hide_tabs_toolbar_v2.css);

/*
Decrease size of the sidebar header.
*/

#sidebar-header {
  font-size: 1.2em !important;
  padding: 2px 6px 2px 3px !important;
}
#sidebar-header #sidebar-close {
  padding: 3px !important;
}
#sidebar-header #sidebar-close .toolbarbutton-icon {
  width: 14px !important;
  height: 14px !important;
  opacity: 0.6 !important;
}

/*
Decrease padding of bookmark menu items.

Based on: https://support.mozilla.org/en-US/questions/1337842
*/


menupopup:not(.in-menulist) > menuitem,
menupopup:not(.in-menulist) > menu {
  padding-block: 2px !important;
}
:root {
  --arrowpanel-menuitem-padding: 4px 8px !important;
}
```
