### ISSUE TITLE
compact_urlbar_megabar.css: URL shift

### ISSUE THREAD

**Issue by Dupond** [MrOtherGuy/firefox-csshacks#491]
Hello!

This post is much more a call for help than a real bug report.

I use the `compact_urlbar_megabar.css` hack. In a new `userChrome.css` file with only the code from this hack, I've added the following lines, in order to hide a few elements in the URL bar:

```
#star-button-box, .urlbar-go-button { display: none; }
#identity-box[pageproxystate="valid"].chromeUI #identity-icon { display: none !important; }
#identity-box[pageproxystate="valid"].chromeUI #identity-icon-label { padding-inline-start: 0 !important; }
```

Here's the result: https://0x0.st/XFEH.png

This doesn't happen with the original URL bar. The height of the text field seems reduced, and does not occupy the full height of the address bar. Is there any way to change this?

Thank you very much for your help, and have a nice day!

**Comment by MrOtherGuy** [comment]
This probably happens because you are hiding star button and go button, becase they are the ones that constrain the height of the input box in this case.

If that is indeed the issue then you can perhaps work around that by adding this:

```css
  #urlbar[breakout-extend]:not([usertyping]) > .urlbar-input-container::after{
    display: flex;
    content: "";
    height: calc(var(--urlbar-min-height) - 2px - 2 * var(--urlbar-container-padding));
  }
```

**Comment by Dupond** [comment]
Thank you very much for your help! Unfortunately, it doesn't work: it doesn't seem to change anything...

**Comment by MrOtherGuy** [comment]
Alright, I just copied that example from another style where a similar thing happens, but only when address bar is in state where it's focused but empty. So to fit it into your use case you need to change it a bit:

```css
#urlbar[breakout] > .urlbar-input-container::after{
  display: flex;
  content: "";
  height: calc(var(--urlbar-min-height) - 2px - 2 * var(--urlbar-container-padding));
}
```
