### ISSUE TITLE
How can i switch place between address bar and tabs?

### ISSUE THREAD

**Issue by waffles38** [MrOtherGuy/firefox-csshacks#498]
So in the image, you can see the address bar is currently to the far left and tabs are in the middle. I want to switch place between these and have the tabs on the far left and the address bar in the middle.
FYI, i am using FF 133.0.3 and these are the mods i currently have in my CSS file:

https://github.com/MrOtherGuy/firefox-csshacks/tree/master/chrome/vertical_bookmarks_toolbar.css
https://github.com/MrOtherGuy/firefox-csshacks/tree/master/chrome/tab_animated_active_border.css
https://github.com/MrOtherGuy/firefox-csshacks/tree/master/chrome/navbar_tabs_oneliner.css

I also have a mod to position the menubar to the far right as can be seen in the image.

Any help with this request is much appreciated. Thank you.

<img width="1507" alt="firefox" src="https://github.com/user-attachments/assets/75a9ba66-f9be-44d5-968d-a15bfc6e5439" />

**Comment by MrOtherGuy** [comment]
[oneline_toolbar.css]() has options with which you can easily select which toolbar is at the left - that style should be used instead of navbar_tabs_oneliner.css from fx 133 onwards anyway.

However, the fact that you also want to display menubar there complicates things. If that's what you desire then I think you should just remove navbar_tabs_oneliner.css and your current menubar mod and use something simple like this instead:

```css
#navigator-toolbox{
  grid-template-columns: 40vw auto min-content;
  display: grid;
}
:where(#navigator-toolbox) > *{
  grid-column: 1/4;
}
#TabsToolbar{
  grid-column: 1/2;
  grid-row: 1;
}
:root[sizemode="normal"] #TabsToolbar > .titlebar-spacer[type="pre-tabs"]{
  display: flex !important;
}
#TabsToolbar > .titlebar-spacer[type="ppost-tabs"]{
  display: none;
}
#nav-bar{
  grid-column: 2/3;
  grid-row: 1;
}
#toolbar-menubar{
  grid-column: 3/4;
  grid-row: 1;
}
#main-menubar{
  height: 100%;
}
#TabsToolbar > .titlebar-buttonbox-container{
  display: none;
}
:root[sizemode="fullscreen"] #toolbar-menubar > .titlebar-buttonbox-container{
  visibility: visible !important;
}
```
