### ISSUE TITLE
Right-click context-menu appearence

### ISSUE THREAD

**Issue by Ghis1964** [MrOtherGuy/firefox-csshacks#507]
Not an issue here I hope. Maybe it's only on my side.

How do I go about making the right-click context-menu the same transparency or similar to the drop-down menu (app-menu/bookmark-menu/etc)?

I've search the most likely css files but can't find the element. Even tried to guess what it would be, ex: #context-menupopup  for one, to no avail.

**Comment by MrOtherGuy** [comment]
This should get you started:

```css
menupopup{
  --panel-background: var(--arrowpanel-background) !important;
  --panel-color: var(--arrowpanel-color) !important;
}
menupopup menu:where([_moz-menuactive]:not([disabled="true"])),
menupopup menuitem:where([_moz-menuactive]:not([disabled="true"])){
  color: inherit !important;
  background-color: var(--panel-item-hover-bgcolor) !important;
}
```

Thing is, there isn't just one right-click context menu, but several. What menupopup is shown just depends on what you happened to right click on. That's why I'm using a generic `menupopup` selector. A side-effect is that other menupopups will now also be styled with this, not just right-click menus - this includes things like menus from menubar.

Also, the styling of context-menus is very much platform specific. The above should work on Windows, but it may not work on Linux. On mac it will almost certainly not work because there Firefox uses native context menus which cannot be styled with CSS - I think that might be the case on some Linux systems as well.
