### ISSUE TITLE
Sometimes the URL bar's position glitches out when using autohide_toolbox.css on Firefox 136.0.1

### ISSUE THREAD

**Issue by LOuroboros** [MrOtherGuy/firefox-csshacks#532]
Title.

I'm not entirely sure how to reproduce this successfully because I'm not checking the URL bar's state permanently over and over, but sometimes, when using the code present in [autohide_toolbox.css](https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/autohide_toolbox.css) almost exclusively, the URL bar jumps from its initial position placing itself below the tabs when you click on it in order to start to write whatever.

I said "*using the code present in autohide_toolbox.css almost exclusively*". That's because I use 1 other little modification to suit my personal needs, one that hides the Minimize/Maximize/Close buttons.

I'm not sure if there's a chance that it's causing this issue, but hopefully someone that knows better can let me know if so 👀

I took a few pictures to better show off what happens on my end.

I click on my URL bar normally, and everything looks fine.

![Image](https://github.com/user-attachments/assets/20681597-cf35-4152-9b08-dd3178b92149)

And then as soon as I start to type, it gets fucky like this: 

![Image](https://github.com/user-attachments/assets/85984a5d-ed51-4cd5-afbe-c2103ce0786a)

This is my userChrome.css right now:

```css
/* ------------------------------------------------------------------------------------------ */

/* Source file https://github.com/MrOtherGuy/firefox-csshacks/tree/master/chrome/autohide_toolbox.css made available under Mozilla Public License v. 2.0
See the above repository for updates as well as full license text. */

/* Hide the whole toolbar area unless urlbar is focused or cursor is over the toolbar
 * Dimensions on non-Win10 OS probably needs to be adjusted.
 */

:root{
  --uc-autohide-toolbox-delay: 200ms; /* Wait 0.1s before hiding toolbars */
  --uc-toolbox-rotation: 82deg;  /* This may need to be lower on mac - like 75 or so */
}

:root[sizemode="maximized"]{
  --uc-toolbox-rotation: 88.5deg;
}

@media  (-moz-platform: windows){
  :root:not([lwtheme]) #navigator-toolbox{ background-color: -moz-dialog !important; }
}

:root[sizemode="fullscreen"],
:root[sizemode="fullscreen"] #navigator-toolbox{ margin-top: 0 !important; }

#navigator-toolbox{
  --browser-area-z-index-toolbox: 3;
  position: fixed !important;
  background-color: var(--lwt-accent-color,black) !important;
  transition: transform 82ms linear, opacity 82ms linear !important;
  transition-delay: var(--uc-autohide-toolbox-delay) !important;
  transform-origin: top;
  transform: rotateX(var(--uc-toolbox-rotation));
  opacity: 0;
  line-height: 0;
  z-index: 1;
  pointer-events: none;
  width: 100vw;
}
:root[sessionrestored] #urlbar[popover]{
  pointer-events: none;
  opacity: 0;
  transition: transform 82ms linear var(--uc-autohide-toolbox-delay), opacity 0ms calc(var(--uc-autohide-toolbox-delay) + 82ms);
  transform-origin: 0px calc(0px - var(--tab-min-height) - var(--tab-block-margin) * 2);
  transform: rotateX(89.9deg);
}
#mainPopupSet:has(> [panelopen]:not(#ask-chat-shortcuts,#tab-preview-panel)) ~ toolbox #urlbar[popover],
#navigator-toolbox:is(:hover,:focus-within,[movingtab]) #urlbar[popover],
#urlbar-container > #urlbar[popover]:is([focused],[open]){
  pointer-events: auto;
  opacity: 1;
  transition-delay: 33ms;
  transform: rotateX(0deg);
}
#mainPopupSet:has(> [panelopen]:not(#ask-chat-shortcuts,#tab-preview-panel)) ~ toolbox,
#navigator-toolbox:has(#urlbar:is([open],[focus-within])),
#navigator-toolbox:is(:hover,:focus-within,[movingtab]){
  transition-delay: 33ms !important;
  transform: rotateX(0);
  opacity: 1;
}
/* This makes things like OS menubar/taskbar show the toolbox when hovered in maximized windows.
 * Unfortunately it also means that other OS native surfaces (such as context menu on macos)
 * and other always-on-top applications will trigger toolbox to show up. */
@media (-moz-bool-pref: "userchrome.autohide-toolbox.unhide-by-native-ui.enabled"),
       -moz-pref("userchrome.autohide-toolbox.unhide-by-native-ui.enabled"){
  :root[sizemode="maximized"]:not(:hover){
    #navigator-toolbox:not(:-moz-window-inactive),
    #urlbar[popover]:not(:-moz-window-inactive){
      transition-delay: 33ms !important;
      transform: rotateX(0);
      opacity: 1;
    }
  }
}

#navigator-toolbox > *{ line-height: normal; pointer-events: auto }

/* Don't apply transform before window has been fully created */
:root:not([sessionrestored]) #navigator-toolbox{ transform:none !important }

:root[customizing] #navigator-toolbox{
  position: relative !important;
  transform: none !important;
  opacity: 1 !important;
}

#navigator-toolbox[inFullscreen] > #PersonalToolbar,
#PersonalToolbar[collapsed="true"]{ display: none }

/* Uncomment this if tabs toolbar is hidden with hide_tabs_toolbar.css */
 /*#titlebar{ margin-bottom: -9px }*/

/* Uncomment the following for compatibility with tabs_on_bottom.css - this isn't well tested though */
/*
#navigator-toolbox{ flex-direction: column; display: flex; }
#titlebar{ order: 2 }
*/

/* ------------------------------------------------------------------------------------------ */

/* Hide the Minimize/Maximize/Close buttons */
/* https://www.reddit.com/r/FirefoxCSS/comments/amby9d */

.titlebar-buttonbox-container{ display: none !important }

#toolbar-menubar spacer {
  display: none !important;
}

/* ------------------------------------------------------------------------------------------ */


```

As I mentioned above, it's really just [autohide_toolbox.css](https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/autohide_toolbox.css) with that extra snippet at the end after a separation bar that I add for readability purposes.

I'm not sure how important it is to mention this too, but I'm using a screen resolution of 1600x900 pixels and my DPI is set to 100%.

I'm using Windows 11 24H2 too.

Thanks in advance for reading, and if there's any other piece of information I need to provide, please let me know!

**Comment by MrOtherGuy** [comment]
I have now added a workaround in 9bf9c83 for the issue triggered by customize mode. I haven't been able to reproduce the exact problem you were describing, but I wonder if the workaround also affects that somehow. I doubt it's going to fix that, but I'd be interested in knowing how it is affected, if at all.

**Comment by LOuroboros** [comment]
> I have now added a workaround in [9bf9c83](https://github.com/MrOtherGuy/firefox-csshacks/commit/9bf9c83944c7a02655b2046bf5366ed0d5f9b296) for the issue triggered by customize mode. I haven't been able to reproduce the exact problem you were describing, but I wonder if the workaround also affects that somehow. I doubt it's going to fix that, but I'd be interested in knowing how it is affected, if at all.

Sadly, the problem is still happening.

![Image](https://github.com/user-attachments/assets/99040f4a-3e02-4351-b744-f96395c3575e)

```css
/* ------------------------------------------------------------------------------------------ */

/* Source file https://github.com/MrOtherGuy/firefox-csshacks/tree/master/chrome/autohide_toolbox.css made available under Mozilla Public License v. 2.0
See the above repository for updates as well as full license text. */

/* Hide the whole toolbar area unless urlbar is focused or cursor is over the toolbar
 * Dimensions on non-Win10 OS probably needs to be adjusted.
 */

:root{
  --uc-autohide-toolbox-delay: 200ms; /* Wait 0.1s before hiding toolbars */
  --uc-toolbox-rotation: 82deg;  /* This may need to be lower on mac - like 75 or so */
}

:root[sizemode="maximized"]{
  --uc-toolbox-rotation: 88.5deg;
}

@media  (-moz-platform: windows){
  :root:not([lwtheme]) #navigator-toolbox{ background-color: -moz-dialog !important; }
}

:root[sizemode="fullscreen"],
:root[sizemode="fullscreen"] #navigator-toolbox{ margin-top: 0 !important; }

#navigator-toolbox{
  --browser-area-z-index-toolbox: 3;
  position: fixed !important;
  background-color: var(--lwt-accent-color,black) !important;
  transition: transform 82ms linear, opacity 82ms linear !important;
  transition-delay: var(--uc-autohide-toolbox-delay) !important;
  transform-origin: top;
  transform: rotateX(var(--uc-toolbox-rotation));
  opacity: 0;
  line-height: 0;
  z-index: 1;
  pointer-events: none;
  width: 100vw;
}
:root[sessionrestored] #urlbar[popover]{
  pointer-events: none;
  opacity: 0;
  transition: transform 82ms linear var(--uc-autohide-toolbox-delay), opacity 0ms calc(var(--uc-autohide-toolbox-delay) + 82ms);
  transform-origin: 0px calc(0px - var(--tab-min-height) - var(--tab-block-margin) * 2);
  transform: rotateX(89.9deg);
}
#mainPopupSet:has(> [panelopen]:not(#ask-chat-shortcuts,#selection-shortcut-action-panel,#chat-shortcuts-options-panel,#tab-preview-panel)) ~ toolbox #urlbar[popover],
#navigator-toolbox:is(:hover,:focus-within,[movingtab]) #urlbar[popover],
#urlbar-container > #urlbar[popover]:is([focused],[open]){
  pointer-events: auto;
  opacity: 1;
  transition-delay: 33ms;
  transform: rotateX(0deg);
}
#mainPopupSet:has(> [panelopen]:not(#ask-chat-shortcuts,#selection-shortcut-action-panel,#chat-shortcuts-options-panel,#tab-preview-panel)) ~ toolbox,
#navigator-toolbox:has(#urlbar:is([open],[focus-within])),
#navigator-toolbox:is(:hover,:focus-within,[movingtab]){
  transition-delay: 33ms !important;
  transform: rotateX(0);
  opacity: 1;
}
/* This makes things like OS menubar/taskbar show the toolbox when hovered in maximized windows.
 * Unfortunately it also means that other OS native surfaces (such as context menu on macos)
 * and other always-on-top applications will trigger toolbox to show up. */
@media (-moz-bool-pref: "userchrome.autohide-toolbox.unhide-by-native-ui.enabled"),
       -moz-pref("userchrome.autohide-toolbox.unhide-by-native-ui.enabled"){
  :root[sizemode="maximized"]:not(:hover){
    #navigator-toolbox:not(:-moz-window-inactive),
    #urlbar[popover]:not(:-moz-window-inactive){
      transition-delay: 33ms !important;
      transform: rotateX(0);
      opacity: 1;
    }
  }
}

#navigator-toolbox > *{ line-height: normal; pointer-events: auto }

/* Don't apply transform before window has been fully created */
:root:not([sessionrestored]) #navigator-toolbox{ transform:none !important }

:root[customizing] #navigator-toolbox{
  position: relative !important;
  transform: none !important;
  opacity: 1 !important;
}

#navigator-toolbox[inFullscreen] > #PersonalToolbar,
#PersonalToolbar[collapsed="true"]{ display: none }

/* This is a bit hacky fix for an issue that will make urlbar zero pixels tall after you enter customize mode */
#urlbar[breakout][breakout-extend] > .urlbar-input-container{
  padding-block: calc(min(4px,(var(--urlbar-container-height) - var(--urlbar-height)) / 2) + var(--urlbar-container-padding)) !important;
}

/* Uncomment this if tabs toolbar is hidden with hide_tabs_toolbar.css */
 /*#titlebar{ margin-bottom: -9px }*/

/* Uncomment the following for compatibility with tabs_on_bottom.css - this isn't well tested though */
/*
#navigator-toolbox{ flex-direction: column; display: flex; }
#titlebar{ order: 2 }
*/

/* ------------------------------------------------------------------------------------------ */

/* Hide the Minimize/Maximize/Close buttons */
/* https://www.reddit.com/r/FirefoxCSS/comments/amby9d */

.titlebar-buttonbox-container{ display: none !important }

#toolbar-menubar spacer {
  display: none !important;
}

/* ------------------------------------------------------------------------------------------ */

/* Hide the "Turn on vertical tabs" context menu option */
/* https://reddit.com/r/firefox/comments/1iim368/hide_the_turn_on_vertical_tabs/mbbzvi5/ */

#toolbar-context-toggle-vertical-tabs {
    display: none !important;
}

#tabContextMenu > menuseparator:nth-child(35) {
    display: none !important;
}

#context_toggleVerticalTabs {
    display: none !important;
}

/* ------------------------------------------------------------------------------------------ */
```
