### ISSUE TITLE
autohide_sidebar.css Activate in Fullscreen Only

### ISSUE THREAD

**Issue by megamorphg** [MrOtherGuy/firefox-csshacks#533]
How can I make it so that autohide_sidebar.css only activates when the browser is in fullscreen?
Typically I only want the side-bar hidden when in full-screen.

**Comment by MrOtherGuy** [comment]
You can totally do that, it just requires a some rather tedious additions. You need to add `:root[sizemode="fullscreen"]` to every selector in the file - this is an example snippet how the start of the file would look like:

```css
:root[sizemode="fullscreen"] #sidebar-box{
  --uc-sidebar-width: 40px;
  --uc-sidebar-hover-width: 210px;
  --uc-autohide-sidebar-delay: 600ms; /* Wait 0.6s before hiding sidebar */
  --uc-autohide-transition-duration: 115ms;
  --uc-autohide-transition-type: linear;
  --browser-area-z-index-sidebar: 3;
  position: relative;
  min-width: var(--uc-sidebar-width) !important;
  width: var(--uc-sidebar-width) !important;
  max-width: var(--uc-sidebar-width) !important;
  z-index: var(--browser-area-z-index-sidebar,3);
}
:root[sizemode="fullscreen"] #sidebar-box[positionend]{ direction: rtl }
:root[sizemode="fullscreen"] #sidebar-box[positionend] > *{ direction: ltr }

:root[sizemode="fullscreen"] #sidebar-box[positionend]:-moz-locale-dir(rtl){ direction: ltr }
:root[sizemode="fullscreen"] #sidebar-box[positionend]:-moz-locale-dir(rtl) > *{ direction: rtl }
```
