### ISSUE TITLE
Blank space at the top in fullscreen video mode with tabs_on_bottom_v2.css

### ISSUE THREAD

**Issue by levinion** [MrOtherGuy/firefox-csshacks#539]
I only use tabs_on_bottom_v2.css, and it works great. However, when a video is in fullscreen mode, there is a small blank space at the top. I believe this is unintended behavior. Is there any way to fix it?

Thanks!

![Image](https://github.com/user-attachments/assets/fe26163c-0c2b-47a6-919b-82fdd5bae25c)

**Comment by MrOtherGuy** [comment]
What OS do you use? On Windows 10 I cannot reproduce this issue, not with 137 or 138.

**Comment by levinion** [comment]
> What OS do you use? On Windows 10 I cannot reproduce this issue, not with 137 or 138.
Linux 6.13.8-zen1-1-zen

**Comment by MrOtherGuy** [comment]
I just tested Nightly 139 on my linux system (Fedora 41 with gnome 47 on wayland) and that doesn't have such issue either. Could you test if this is really caused by tabs_on_bottom_v2.css or if the issue also happens without any custom css?

**Comment by levinion** [comment]
> I just tested Nightly 139 on my linux system (Fedora 41 with gnome 47 on wayland) and that doesn't have such issue either. Could you test if this is really caused by tabs_on_bottom_v2.css or if the issue also happens without any custom css?

Yes, I tried to reproduce the issue using the following steps:

1. Changed the window manager. I switched from i3 (using X11) to Hyprland (using Wayland) and was able to reproduce the issue.
2. Created a new profile (with all settings default and no sync, meaning no extensions or third-party themes), and the issue did not occur. Then, I enabled stylesheets in the configuration, copied chrome to the new profile, and played a video—the issue reappeared.

`chrome` contains nothing but the .css, and there's only a single line `@import` in `userChrome.css`:

![Image](https://github.com/user-attachments/assets/fb154cd1-58ad-41f7-8d55-4182cd3dbbae)

And I hope the information below will be helpful:

- Firefox version: Mozilla Firefox 138.0b2
- OS: Arch Linux x86_64
- Kernel: Linux 6.13.8-zen1-1-zen
- WM:  i3 (X11)

Thanks for your help again!

**Comment by MrOtherGuy** [comment]
I don't have beta or developer edition installed, but I tested with Firefox 137 which you said is also affected and I'm still unable to reproduce the issue. So as it stands I unfortunately cannot do much about this. The best way forward might be for you to basically remove some rulesets one by one from tabs_on_bottom_v2.css until the issue doesn't happen anymore. Lines [25-27](https://github.com/MrOtherGuy/firefox-csshacks/blob/9bf9c83944c7a02655b2046bf5366ed0d5f9b296/chrome/tabs_on_bottom_v2.css#L25-L27) feel like they could plausibly cause this issue, although I don't know what exactly is different on your system that those rules would become an issue. Still, it's a starting point.

**Comment by levinion** [comment]
> I don't have beta or developer edition installed, but I tested with Firefox 137 which you said is also affected and I'm still unable to reproduce the issue. So as it stands I unfortunately cannot do much about this. The best way forward might be for you to basically remove some rulesets one by one from tabs_on_bottom_v2.css until the issue doesn't happen anymore. Lines [25-27](https://github.com/MrOtherGuy/firefox-csshacks/blob/9bf9c83944c7a02655b2046bf5366ed0d5f9b296/chrome/tabs_on_bottom_v2.css#L25-L27) feel like they could plausibly cause this issue, although I don't know what exactly is different on your system that those rules would become an issue. Still, it's a starting point.

No, I commented out these lines, but the issue still persists. I’d like to leave this issue open to see if anyone else encounters the same problem. Thanks for your help.

**Comment by levinion** [comment]
I found that it was a 20px high toolbar with the ID nav-bar, and I added the rule below to hide it. Now it looks good.

```css
:root[inDOMFullscreen] #nav-bar {
  display: none !important;
```

<img width="1820" height="1106" alt="Image" src="https://github.com/user-attachments/assets/99201b3f-fccb-4119-91b6-06933bfe4b77" />

I'm not sure why it showed up, but the problem is fixed with the method above.To troubleshoot the issue, I used a more simplified version, which may help pinpoint the problem, if you'd like to find out the reason.

```css
@media not (-moz-bool-pref: "sidebar.verticalTabs"),
not -moz-pref("sidebar.verticalTabs") {
  #main-window>body {
    display: grid !important;
    grid-template-rows: repeat(8, max-content) 1fr;
  }

  #navigator-toolbox {
    display: contents;
  }

  #main-window #browser {
    grid-row: 9/10;
  }

  #TabsToolbar {
    grid-row: 10/11;
  }

  #TabsToolbar> :is(.titlebar-buttonbox-container, .titlebar-spacer) {
    display: none;
  }
}

:root[inDOMFullscreen] #nav-bar {
  display: none !important;
}

```

Thanks for your help again!
