### ISSUE TITLE
Multi row tabs below address bar (no title bar and window controls)

### ISSUE THREAD

**Issue by AlexFundorin** [MrOtherGuy/firefox-csshacks#54]
Which combination of script should be used to get the type of UI from the subject?

**Comment by MrOtherGuy** [comment]
```css
@import url("chrome/window_control_placeholder_support.css");
@import url("chrome/Fx65_tabs_on_bottom.css");
@import url("chrome/multi-row_tabs.css");
```

That should work. Although, I'm not sure how to interpret your title regarding window controls.
The above should show window controls in the main toolbar. If you meant that you do not want window controls to show up then you can ignore the first file but add this instead after the imports:

```css
#TabsToolbar > .titlebar-buttonbox-container{ display: none }
```

**Comment by AlexFundorin** [comment]
Thanks. Almost what I wanted.
The thing is that now I have a set of window controls over the address bar icons.
https://i.imgur.com/EPMu5Ua.png
https://i.imgur.com/aBiQqno.png

I would like to get rid of it, completely.

**Comment by MrOtherGuy** [comment]
The code above `#TabsToolbar > .titlebar-buttonbox-container{ display: none }` should hide those. Unless you are using some custom Windows theme then it might not do so, and I don't think any CSS will help you do that if that is the case.

**Comment by MrOtherGuy** [comment]
No, actually it that setup should hide the icons, but the buttons in navbar could still be "blocked" by invisible window control buttons.

You should use this instead (with the imports of course):

```css
#titlebar > .browser-toolbar > .titlebar-buttonbox-container{ display: none }
```

**Comment by AlexFundorin** [comment]
I checked it again. Didn't copy the first symbol '#'. My mistake. Thanks again.
I can almost use Firefox again now, switching from Waterfox.

**Comment by AlexFundorin** [comment]
I used your second suggestion (together with other imports. In regular mode, everything's looking fine, including multi row.
Yet, as soon as I switch to full screen, this happens: https://i.imgur.com/lNmyH4i.png

Do, you, by any chance, know how to add a small empty area at the end of the tab bar, so it would be possible to drag the window?

**Comment by MrOtherGuy** [comment]
Dang, yeeah I forgot about fullscreen.

```css
#window-controls,
#titlebar > .browser-toolbar > .titlebar-buttonbox-container{ display: none }

#nav-bar{ padding-inline: 12px }
```

\#window-controls would also hie those in fullscreen mode. The other creates a 12px wide empty area on both sides of main toolbar to drag the window around.
