### ISSUE TITLE
the search engines toolbar is floating when using toolbars_below_content_v2/toolbars_below_content

### ISSUE THREAD

**Issue by artemlive** [MrOtherGuy/firefox-csshacks#553]
Hello, folks. Can someone help me with the problem that I shared in the screenshots?
This toolbar comes out on every page at the same floating position, and I can do nothing with it. 
I'm currently using the toolbars_below_content_v2 version. 

I'd appreciate any advice. Thanks!

<img width="1548" alt="Image" src="https://github.com/user-attachments/assets/9ed93149-912c-4159-a899-0e1b242ffaaa" />

<img width="1491" alt="Image" src="https://github.com/user-attachments/assets/926e6d03-502f-4a9e-91b2-040bd5470288" />

**Comment by MrOtherGuy** [comment]
I'm pretty sure that this thing is the search engine selector and it's supposed to be the left-most item inside urlbar (provided that the feature is enabled). I don't know why you have it shown in the middle of the screen though, on my Windows and Linux systems that thing is in its correct position inside urlbar when using toolbars_below_content_v2. But supposing that you don't want that feature enabled then you might be able to disable it by going to about:config and setting `browser.urlbar.scotchBonnet.enableOverride` to false.

**Comment by todated** [comment]
i also had this issue with `navbar_below_content.css` (single monitor, linux)

i did not disable the `scotchBonnet` / `searchmode-switcher` but was able to work around it with:

```css
@import url(chrome/navbar_below_content.css);
@-moz-document url(chrome://browser/content/browser.xhtml) {
  .searchmode-switcher {
    position: unset !important;
  }
}
```
