### ISSUE TITLE
Not working w/more than 3 rows

### ISSUE THREAD

**Issue by DubDublin** [MrOtherGuy/firefox-csshacks#7]
I am not able to get this working with more than 3 rows, no matter what I try (although I'm admittedly a baby FF chrome hacker...)  

(Using FF 66.0.2 on Win 10 Pro 1809. Extensions: Dissenter Extension, OneNote Web Clipper, PrintEdit WE, PrivacyBadger, Table to Excel, WhatRuns)

Try changing --multirow-n-rows: 4; (or more - I want ~5 for my 4K monitor) and see if it works for you.

**Comment by MrOtherGuy** [comment]
It works just fine for me (as does 5, 6, 7 ....). Maybe different display scaling affects this? I don't think it should but I can't think of anything else at the moment.

**Comment by Zachu** [comment]
I realize this is an ancient issue but I was having the same issue and got it fixed by specifying `--tab-block-margin`. My working `userChrome.css`:
```css
@import url(chrome/multi-row_tabs.css);

:root{
  --tab-block-margin: 2px !important;
  --multirow-n-rows: 6 !important;
  --multirow-tab-min-width: 120px !important;
  --multirow-tab-dynamic-width: 0 !important;
}
```
