### ISSUE TITLE
autohide_bookmarks_and_main_toolbars not working on FF 81.0.1

### ISSUE THREAD

**Issue by oblitum** [MrOtherGuy/firefox-csshacks#79]
I'm on Archlinux. The auto-hide isn't working correctly regarding the tab bar, I can't describe much how the tab bar is being display, but it's scrambled, half hidden, half displayed, mixed with the page contents:

![14:48:20_04-10-2020](https://user-images.githubusercontent.com/1269815/95023040-2a7ec200-0651-11eb-9684-86dcec67f5c4.png)

![14:49:41_04-10-2020](https://user-images.githubusercontent.com/1269815/95023116-93663a00-0651-11eb-8fbf-cdeda68771e4.png)

**Comment by MrOtherGuy** [comment]
I believe it is actually working as intended. It's just that if you don't have bookmarks toolbar enabled then you will face that very weird layout.

So just simply enable boookmarks toolbar and should work. The current iteration just doesn't work with bookmark toolbar enabled. 

I would like to make it work with or without bookmarks toolbar though, so I'll look into this a bit if I could somehow do that. But I'm pretty sure I would've done that when I wrote that style if it would have been somewhat simple - so don't get your hopes up.

**Comment by oblitum** [comment]
You're right, enabling the bookmarks toolbar make it work.

The thing is, I guess this is now that I wished... I actually wish to hide all the toolbars. autohide_bookmarks_and_main_toolbars will not hide the tab bar, and importing autohide_tabstoolbar doesn't hide it either, it'll only cause lots of flickering when hovering.

Before trying your work, I simply used this to attain what I want:

```css
#navigator-toolbox {
  position: relative;
  z-index: 1;
  height: 3px;
  margin-bottom: -3px;
  opacity: 0;
  overflow: hidden;
}
#navigator-toolbox:hover {
  height: auto;
  margin-bottom: 0px;
  opacity: 1;
  overflow: show;
}
#content-deck {
  position: relative;
  z-index: 0;
}
```

This worked pretty well in Firefox Quantum, until FF80 when this started to hide the autocompletion results in the search box, I guess to some z-index conflict I don't have much idea how to fix. Any help appreciated.
