### ISSUE TITLE
Any way to (completely) hide tab bar, with urlbar at the bottom?

### ISSUE THREAD

**Issue by SeerLite** [MrOtherGuy/firefox-csshacks#80]
Hi!
I want to have only the "urlbar" at the bottom of the window. I tried the following combinations:
* `navbar_below_content` + `hide_tabs_toolbar`
* `toolbars_below_content` + `hide_tabs_toolbar`

The first one leaves an empty "placeholder"-like bar at the bottom where tabs would be, and the second one does the same but at the top.
Is there any combination/style that can leave only the urlbar at the bottom, without these "side effects"? I'm on (Arch) Linux in case it matters.

Thanks!

**Comment by MrOtherGuy** [comment]
You would probably like to just use something super simple for that. Like this maybe:
```css
body > box { -moz-box-ordinal-group: 2 }
#titlebar{ visibility: collapse }
```

Then maybe just grab few lines from nav-bar-below content to flip the direction of urlbar popup, so these:

```css
  #urlbar[breakout][breakout-extend]{
    display: flex !important;
    flex-direction: column-reverse;
    bottom: -2px !important; /* Change to 3-5 px if using compact_urlbar_megabar.css depending on toolbar density */
    top: auto !important;
  }

  #urlbar[open] > .urlbarView{ margin-block: 0px calc(var(--urlbar-height) + 1px) !important; box-shadow: none !important; }
```
