### ISSUE TITLE
compact_urlbar_megabar.css applies wrong padding to #identity-box on Firefox protected pages

### ISSUE THREAD

**Issue by TheFineBroccoli** [MrOtherGuy/firefox-csshacks#81]
Hi! I noticed that the padding applied to `#identity-box` is broken on protected pages

![broken](https://user-images.githubusercontent.com/46381898/96712558-9ece9a80-139f-11eb-9a9b-361c248bda14.png)

Removing/commenting out this rule fixes the issue 
https://github.com/MrOtherGuy/firefox-csshacks/blob/5e823bafd54a966558837f7977bee1a3bc74948a/chrome/compact_urlbar_megabar.css#L17

![normal](https://user-images.githubusercontent.com/46381898/96712770-e9501700-139f-11eb-932e-c3b0055ae7e3.png)

~~And nothing else seems to be broken when it's removed.~~

Just found that it breaks the height of `#urlbar-input-container`, could there be a way around this?

Firefox 81.0.2, Linux

**Comment by MrOtherGuy** [comment]
Can you check if that happens on other non-http(s) pages too? Like extension pages or file:// uri?

**Comment by MrOtherGuy** [comment]
I think chances are it's wrong whenever the identity has some label in text.

**Comment by MrOtherGuy** [comment]
Actually that padding was added specifically for the purpose to prevent such offsets from happening. But I guess internal style has changed since so I can just remove that padding rule altogether - that's always nice.

Fixed in #16a4cd3d5bb43c811209da9ffe49f90a4118e66c

**Comment by TheFineBroccoli** [comment]
@MrOtherGuy Sorry for not getting back to you sooner, I did some testing and it turns out that the padding wasn't really unnecessary. It's only needed when the `#urlbar` is in focused state, but it's too big for protected pages, so I added these two lines (instead of the `#identity-box{ padding-block: var(--urlbar-icon-padding) }`):

```css
#urlbar[focused="true"] #identity-box{ padding-block: var(--urlbar-icon-padding) !important; }
#urlbar[focused="true"] #identity-box[pageproxystate="valid"]{ padding-block: calc(var(--urlbar-icon-padding) / 2) !important; }
```
And everything seems to work as expected, without any weird height shifting as it did without the padding
