### ISSUE TITLE
Making an app mode style

### ISSUE THREAD

**Issue by dragahassan** [MrOtherGuy/firefox-csshacks#84]
I'm trying to make a style like "chrome --app" mode. I set everything I need, except we lose [min][max][close]. Any one have another way?

```
#toolbar-menubar {visibility: collapse;}
#urlbar {visibility: collapse;}
#searchbar {visibility: collapse;}
#find-field-container {visibility: collapse;}
#throbber {visibility: collapse;}
#bookmarks-menu {visibility: collapse;}
#nav-bar {visibility: collapse;}
#TabsToolbar {visibility: collapse;}
```

![firefox_app_mode](https://user-images.githubusercontent.com/61518789/97758403-8e27ce00-1add-11eb-8ce4-884fe07ba83a.png)

**Comment by MrOtherGuy** [comment]
Enable menubar in Firefox customization and then you can use something like this:

```css
#menubar-items{visibility: collapse;}
#find-field-container {visibility: collapse;}
#nav-bar {visibility: collapse;}
#TabsToolbar {visibility: collapse;}
```

Sidenote, if you want to show the window title in that empty area then you can use [this style](https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/show_window_title_in_menubar.css) - just replace the `calc(100vw - 440px)` with something like `calc(100vw - 140px)`
